if(!document.querySelector('link[href$="portal.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/portal.css';document.head.append(l)}if(!document.querySelector('script[src$="navigation.js"]')){const s=document.createElement('script');s.src='/navigation.js';document.head.append(s)}
const STORE_WHATSAPP_NUMBER = '';
const store = { name: 'Loja do Preto', whatsapp: STORE_WHATSAPP_NUMBER };
const whatsappIcon='<span class="wa-icon" aria-hidden="true"></span>';

let vehicles = [
  {id:'demo-001',brand:'Toyota',model:'Corolla',version:'XEi',year:2024,mileage:32000,transmission:'Automático',fuel:'Flex',color:'Preto',category:'Sedan',price:null,installment:null,featured:true,image:'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',whatsappNumber:'',whatsappMessage:'',features:[]},
  {id:'demo-002',brand:'Jeep',model:'Compass',version:'Limited',year:2023,mileage:41000,transmission:'Automático',fuel:'Flex',color:'Grafite',category:'SUV',price:null,installment:null,featured:true,image:'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',whatsappNumber:'',whatsappMessage:'',features:[]},
  {id:'demo-003',brand:'BMW',model:'320i',version:'Sport GP',year:2022,mileage:38000,transmission:'Automático',fuel:'Gasolina',color:'Preto',category:'Sedan',price:null,installment:null,featured:true,image:'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',whatsappNumber:'',whatsappMessage:'',features:[]},
  {id:'demo-004',brand:'Volkswagen',model:'T-Cross',version:'Highline',year:2023,mileage:29000,transmission:'Automático',fuel:'Flex',color:'Prata',category:'SUV',price:null,installment:null,featured:false,image:'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',whatsappNumber:'',whatsappMessage:'',features:[]},
  {id:'demo-005',brand:'Honda',model:'Civic',version:'Touring',year:2021,mileage:52000,transmission:'Automático',fuel:'Gasolina',color:'Branco',category:'Sedan',price:null,installment:null,featured:false,image:'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',whatsappNumber:'',whatsappMessage:'',features:[]},
  {id:'demo-006',brand:'Chevrolet',model:'Tracker',version:'Premier',year:2024,mileage:18000,transmission:'Automático',fuel:'Flex',color:'Preto',category:'SUV',price:null,installment:null,featured:false,image:'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',whatsappNumber:'',whatsappMessage:'',features:[]}
];

const money = n => n ? Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}) : 'Consulte o valor';
const messageFor = v => v.whatsappMessage || `Olá! Tenho interesse no ${v.brand} ${v.model} ${v.version} ${v.year} anunciado no site da Loja do Preto. Gostaria de receber mais informações e conhecer as condições de negociação.`;
function waLink(message, number=store.whatsapp){ const clean=(number||'').replace(/\D/g,''); return clean ? `https://wa.me/${clean}?text=${encodeURIComponent(message)}` : `https://wa.me/?text=${encodeURIComponent(message+'\n\n[WhatsApp da loja ainda será configurado no site.]')}`; }
function bindWhatsApp(root=document){ root.querySelectorAll('[data-wa]').forEach(a=>{a.href=waLink(a.dataset.message||'Olá! Gostaria de falar com a Loja do Preto.');a.target='_blank';a.rel='noopener';if(!a.querySelector('.wa-icon')){a.innerHTML=a.innerHTML.replace(/^\s*◉\s*/,'');a.insertAdjacentHTML('afterbegin',whatsappIcon)}}); }

function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(v){const kind=(v.vehicle_type||'car')==='motorcycle'?'moto':'carro';const status=v.status||'available',statusLabel={available:'Disponível',reserved:'Reservado',sold:'Vendido'}[status];const saved=getFavorites().includes(String(v.id)),compared=getCompare().includes(String(v.id));return `<article class="vehicle-card ${status}"><div class="vehicle-photo"><img src="${esc(v.image)}" alt="${esc(v.brand)} ${esc(v.model)}" loading="lazy">${v.featured?'<span class="tag">DESTAQUE</span>':''}${v.newly_arrived?'<span class="new-badge">NOVO NO ESTOQUE</span>':''}<div class="vehicle-actions-top"><button class="${saved?'active':''}" data-favorite="${v.id}" aria-label="${saved?'Remover dos':'Adicionar aos'} favoritos"><svg class="card-action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.7Z"/></svg></button><button class="${compared?'active':''}" data-compare="${v.id}" aria-label="Comparar veículo"><svg class="card-action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 7-3 3 3 3M4 10h12M17 17l3-3-3-3M20 14H8"/></svg></button></div><span class="vehicle-status ${status}">${statusLabel}</span></div><div class="vehicle-body"><div class="vehicle-title-row"><div><h3>${esc(v.brand)} ${esc(v.model)}</h3><p class="version">${esc(v.version||'Versão a consultar')}</p></div><p class="price">${money(v.price)}</p></div><ul class="vehicle-spec-list"><li>${esc(v.year)}</li><li>${Number(v.mileage||0).toLocaleString('pt-BR')} km</li><li>${esc(v.transmission||'Câmbio a consultar')}</li><li>${esc(v.fuel||'Combustível a consultar')}</li></ul><a class="btn ${status==='sold'?'btn-dark':'btn-wa'} vehicle-cta" data-wa data-message="${esc(status==='sold'?`Olá! Vi o ${v.brand} ${v.model} ${v.year}, que já foi vendido. Gostaria de encontrar um parecido.`:messageFor(v))}">${status==='sold'?'Encontrar um parecido':'Falar sobre este veículo'}</a><div class="vehicle-secondary"><button data-detail="${v.id}">Visualização rápida</button><a href="vehicle.html?slug=${encodeURIComponent(v.slug||v.id)}">Ver detalhes</a></div></div></article>`}
const featuredGrid=document.querySelector('#featured-grid'), inventoryGrid=document.querySelector('#inventory-grid');
featuredGrid.innerHTML=vehicles.filter(v=>v.featured).map(card).join('');
let filters={};
function renderInventory(){let list=vehicles.filter(v=>v.active!==false&&(v.status!=='sold'||v.keep_sold_public!==false)&&(!filters.vehicle_type||(v.vehicle_type||'car')===filters.vehicle_type)&&(!filters.brand||v.brand===filters.brand)&&(!filters.model||v.model===filters.model)&&(!filters.minYear||v.year>=+filters.minYear)&&(!filters.maxYear||v.year<=+filters.maxYear)&&(!filters.transmission||v.transmission===filters.transmission)&&(!filters.maxPrice||!v.price||v.price<=+filters.maxPrice)&&(!filters.query||matchesNaturalSearch(v,filters.query))&&(!filters.intent||matchesIntent(v,filters.intent))&&(!filters.favorite||getFavorites().includes(String(v.id))));const order=document.querySelector('#sort').value;if(order==='low')list.sort((a,b)=>(a.price||Infinity)-(b.price||Infinity));if(order==='high')list.sort((a,b)=>(b.price||0)-(a.price||0));if(order==='mileage')list.sort((a,b)=>a.mileage-b.mileage);inventoryGrid.classList.remove('skeleton-grid');inventoryGrid.innerHTML=list.map(card).join('');document.querySelector('#result-count').textContent=`${list.length} veículo${list.length===1?'':'s'} disponíve${list.length===1?'l':'is'}`;document.querySelector('#empty').style.display=list.length?'none':'block';bindWhatsApp();bindDetails();bindCardActions();renderAuxiliaryCollections();}
const brand=document.querySelector('[name=brand]'),model=document.querySelector('[name=model]');[...new Set(vehicles.map(v=>v.brand))].sort().forEach(x=>brand.add(new Option(x,x)));[...new Set(vehicles.map(v=>v.model))].sort().forEach(x=>model.add(new Option(x,x)));
document.querySelector('#quick-form').addEventListener('submit',e=>{e.preventDefault();filters=Object.fromEntries(new FormData(e.currentTarget));renderInventory();document.querySelector('#estoque').scrollIntoView();});document.querySelector('#clear-filters').onclick=()=>{filters={};document.querySelector('#quick-form').reset();renderInventory()};document.querySelector('#sort').onchange=renderInventory;

const modal=document.querySelector('#vehicle-modal');function bindDetails(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openVehicleEnhanced(vehicles.find(v=>String(v.id)===String(b.dataset.detail))));}
function openVehicle(v){history.replaceState(null,'',`#estoque/${v.brand}-${v.model}-${v.year}`.toLowerCase().replaceAll(' ','-'));const features=v.features?.length?v.features.join(' • '):'Consulte nossa equipe para conhecer os equipamentos e detalhes deste veículo.';document.querySelector('#modal-content').innerHTML=`<div class="modal-layout"><img class="modal-photo" src="${v.image}" alt="${v.brand} ${v.model}"><div class="modal-info"><p class="eyebrow dark">Disponível no estoque</p><h2>${v.brand} ${v.model}</h2><p>${v.version||'Consulte a versão'}</p><div class="modal-specs"><div><b>Ano</b><br>${v.year}</div><div><b>Quilometragem</b><br>${Number(v.mileage||0).toLocaleString('pt-BR')} km</div><div><b>Câmbio</b><br>${v.transmission||'Consulte'}</div><div><b>Combustível</b><br>${v.fuel||'Consulte'}</div><div><b>Cor</b><br>${v.color||'Consulte'}</div><div><b>Categoria</b><br>${v.category||'Consulte'}</div></div><p class="price">${money(v.price)}</p><p><b>${v.installment?'Parcelas a partir de '+money(v.installment)+'/mês':'Consulte as condições de financiamento'}</b></p><div class="modal-actions"><a class="btn btn-wa" data-wa data-message="${messageFor(v)}">◉ Tenho interesse — falar no WhatsApp</a><a href="#financiamento" class="btn btn-dark" onclick="document.querySelector('#vehicle-modal').close()">Simular financiamento</a><a href="#avaliacao" class="details-btn" onclick="document.querySelector('#vehicle-modal').close()">Tenho um veículo para dar na troca</a></div><h3>Destaques e equipamentos</h3><p>${features}</p></div></div>`;bindWhatsApp(document.querySelector('#modal-content'));modal.showModal();}
document.querySelector('.modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

const defaultFaqs=['Os veículos possuem garantia?','Vocês aceitam carro usado na troca?','Posso financiar meu veículo?','Posso fazer uma simulação pelo WhatsApp?','Posso agendar uma visita?','Os veículos passam por avaliação?','Vocês entregam veículos em outras cidades?'].map(question=>({question,answer:'Consulte nossa equipe para verificar as condições aplicáveis a este veículo e à negociação.'}));function renderFaqs(items=defaultFaqs){document.querySelector('#faq-list').innerHTML=items.map(item=>`<div class="faq-item"><button aria-expanded="false">${esc(item.question||item.q||'Dúvida')}<span>＋</span></button><div class="faq-answer">${esc(item.answer||item.a||'Consulte nossa equipe.')}</div></div>`).join('');document.querySelectorAll('.faq-item button').forEach(b=>b.onclick=()=>{const p=b.parentElement,willOpen=!p.classList.contains('open');document.querySelectorAll('.faq-item.open').forEach(x=>{x.classList.remove('open');x.querySelector('button').setAttribute('aria-expanded','false');x.querySelector('button span').textContent='＋'});p.classList.toggle('open',willOpen);b.setAttribute('aria-expanded',willOpen);b.querySelector('span').textContent=willOpen?'−':'＋'})}renderFaqs();

function digits(v){return Number((v||'').replace(/\D/g,''))||0}document.querySelector('#finance-form').addEventListener('input',e=>{const f=e.currentTarget;const financed=Math.max(0,digits(f.value.value)-digits(f.down.value));const installment=financed?financed/+f.months.value*1.018:0;document.querySelector('#estimate').textContent=installment?money(installment)+' /mês':'R$ — /mês'});
function handleForm(id,type){document.querySelector(id).addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,status=f.querySelector('.form-status');if(!f.checkValidity()){f.reportValidity();status.textContent='Revise os campos obrigatórios.';return}status.textContent='Preparando sua solicitação…';setTimeout(()=>{const d=Object.fromEntries(new FormData(f));status.textContent='Recebemos sua solicitação! Abrindo o WhatsApp para continuar.';window.open(waLink(`Olá! Quero continuar minha solicitação de ${type}.\nDados: ${Object.entries(d).map(([k,v])=>`${k}: ${v}`).join(' | ')}`),'_blank')},500)})}handleForm('#finance-form','financiamento');handleForm('#trade-form','avaliação do meu carro');
document.querySelectorAll('[name=phone]').forEach(i=>i.addEventListener('input',()=>{let v=i.value.replace(/\D/g,'').slice(0,11);i.value=v.replace(/(\d{2})(\d{5})(\d{0,4})/,'($1) $2-$3')}));document.querySelector('.menu').onclick=e=>{const n=document.querySelector('#nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))};document.querySelector('.filter-toggle').onclick=e=>{const f=document.querySelector('.filter-grid');f.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',f.classList.contains('open'));e.currentTarget.textContent=f.classList.contains('open')?'Fechar filtros':'Abrir filtros'};
async function loadRemoteContent(){
  if(!window.supabaseClient) return;
  try{
    const [{data:remoteVehicles,error:vehicleError},{data:settings,error:settingsError}]=await Promise.all([
      window.supabaseClient.from('vehicles').select('*').eq('active',true).order('created_at',{ascending:false}),
      window.supabaseClient.from('store_settings').select('*').eq('id',1).maybeSingle()
    ]);
    if(vehicleError||settingsError) throw vehicleError||settingsError;
    if(settings){
      if(settings.whatsapp) store.whatsapp=settings.whatsapp;
      const setText=(id,label,value,fallback)=>{const el=document.querySelector(id);if(el)el.textContent=value?`${label}: ${value}`:fallback};
      const name=document.querySelector('#footer-store-name');if(name&&settings.store_name)name.childNodes[0].nodeValue=settings.store_name.toUpperCase();
      setText('#footer-whatsapp','WhatsApp',settings.whatsapp,'WhatsApp: consulte nossa equipe');
      setText('#footer-phone','Telefone',settings.phone,'Telefone: consulte nossa equipe');
      setText('#footer-email','E-mail',settings.email,'E-mail: consulte nossa equipe');
      setText('#footer-address','Endereço',settings.address,'Endereço: consulte nossa equipe');
      const hours=document.querySelector('#footer-hours');if(hours)hours.textContent=settings.business_hours||'Consulte os horários de atendimento com nossa equipe.';
      const instagram=document.querySelector('#footer-instagram');if(instagram)instagram.textContent=settings.instagram?`Instagram: ${settings.instagram}`:'Instagram da Loja do Preto';
      if(settings.hero_title){const parts=settings.hero_title.split(/\s+(?=[^\s]+$)/);document.querySelector('.hero h1').innerHTML=`<span>${esc(parts.slice(0,-1).join(' ')||settings.hero_title)}</span>${parts.length>1?`<br><em>${esc(parts.at(-1))}</em>`:''}`}
      if(settings.hero_subtitle)document.querySelector('.hero .lead').textContent=settings.hero_subtitle;
      if(settings.hero_wordmark)document.querySelector('.hero-wordmark').textContent=settings.hero_wordmark;
      if(settings.hero_image_url)document.querySelector('.hero-bg').style.backgroundImage=`url("${settings.hero_image_url.replace(/["\\]/g,'')}")`;
      if(Array.isArray(settings.faqs)&&settings.faqs.length)renderFaqs(settings.faqs);
      if(Array.isArray(settings.lifestyle_categories)&&settings.lifestyle_categories.length)store.lifestyleCategories=settings.lifestyle_categories;
    }
    if(remoteVehicles?.length){
      vehicles=remoteVehicles.map(v=>({
        ...v,
        image:v.image_url||'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg',
        whatsappNumber:v.whatsapp_number||'',
        whatsappMessage:v.whatsapp_message||'',
        features:v.features||[]
      }));
      featuredGrid.innerHTML=vehicles.filter(v=>v.featured).map(card).join('');
      brand.innerHTML='<option value="">Todas</option>';model.innerHTML='<option value="">Todos</option>';
      [...new Set(vehicles.map(v=>v.brand))].sort().forEach(x=>brand.add(new Option(x,x)));
      [...new Set(vehicles.map(v=>v.model))].sort().forEach(x=>model.add(new Option(x,x)));
      renderInventory();bindDetails();
    }
    bindWhatsApp();
  }catch(error){console.warn('Conteúdo remoto indisponível; usando dados demonstrativos.',error.message)}
}
bindWhatsApp();renderInventory();loadRemoteContent();
if(window.supabaseClient){
  window.supabaseClient.channel('site-content')
    .on('postgres_changes',{event:'*',schema:'public',table:'vehicles'},loadRemoteContent)
    .on('postgres_changes',{event:'*',schema:'public',table:'store_settings'},loadRemoteContent)
    .subscribe();
}

/* Discovery, conversion and showroom experience */
const storageRead=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const storageWrite=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
function getFavorites(){try{return JSON.parse(localStorage.getItem('ldp-favorites'))||[]}catch{return []}}
function getCompare(){try{return JSON.parse(localStorage.getItem('ldp-compare'))||[]}catch{return []}}
function normalize(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function vehicleText(v){return normalize([v.brand,v.model,v.version,v.year,v.transmission,v.fuel,v.color,v.category,...(v.features||[]),...(v.tags||[])].join(' '))}
function matchesNaturalSearch(v,query){const q=normalize(query),text=vehicleText(v);const priceMatch=q.match(/(?:ate|até)\s*(\d+)/);if(priceMatch&&v.price&&Number(v.price)>Number(priceMatch[1])*(Number(priceMatch[1])<1000?1000:1))return false;return q.replace(/(?:ate|até)\s*\d+\s*(?:mil)?/g,'').split(/\s+/).filter(Boolean).every(term=>term==='mil'||text.includes(term))}
function matchesIntent(v,intent){if(intent==='low-mileage')return Number(v.mileage||0)<=40000;if(/^\d+$/.test(intent))return !v.price||Number(v.price)<=Number(intent);return vehicleText(v).includes(normalize(intent))}
function track(name,detail={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...detail});window.dispatchEvent(new CustomEvent('ldp:conversion',{detail:{name,...detail}}))}

function updateFavoriteUI(){const count=getFavorites().length;document.querySelectorAll('#nav-favorites b,#mobile-favorites b').forEach(el=>el.textContent=count)}
function bindCardActions(){document.querySelectorAll('a[href^="vehicle.html?slug="]').forEach(a=>a.href=`/vehicle?slug=${encodeURIComponent(new URL(a.href,location.href).searchParams.get('slug'))}`);document.querySelectorAll('[data-favorite]').forEach(button=>button.onclick=()=>{const id=String(button.dataset.favorite),items=getFavorites(),next=items.includes(id)?items.filter(x=>x!==id):[...items,id];storageWrite('ldp-favorites',next);track('favorite_vehicle',{vehicle_id:id,action:next.includes(id)?'save':'remove'});updateFavoriteUI();renderInventory()});document.querySelectorAll('[data-compare]').forEach(button=>button.onclick=()=>{const id=String(button.dataset.compare),items=getCompare();let next=items.includes(id)?items.filter(x=>x!==id):items.length<3?[...items,id]:items;storageWrite('ldp-compare',next);track('compare_vehicle',{vehicle_id:id,selected:next.includes(id)});renderCompareTray();renderInventory()})}

function renderCompareTray(){const ids=getCompare(),tray=document.querySelector('#compare-tray');tray.hidden=!ids.length;document.querySelector('#compare-summary').textContent=`${ids.length} de 3 selecionados`;document.querySelector('#compare-items').innerHTML=ids.map(id=>{const v=vehicles.find(x=>String(x.id)===id);return v?`<span class="compare-chip">${esc(v.brand)} ${esc(v.model)}</span>`:''}).join('');document.querySelector('#open-compare').disabled=ids.length<2}
function openCompare(){const selected=getCompare().map(id=>vehicles.find(v=>String(v.id)===id)).filter(Boolean);const rows=[['Ano',v=>v.year],['Quilometragem',v=>`${Number(v.mileage||0).toLocaleString('pt-BR')} km`],['Câmbio',v=>v.transmission||'Consulte'],['Combustível',v=>v.fuel||'Consulte'],['Preço',v=>money(v.price)]];document.querySelector('#compare-table').innerHTML=`<table class="compare-table"><thead><tr><th>Característica</th>${selected.map(v=>`<th>${esc(v.brand)} ${esc(v.model)}</th>`).join('')}</tr></thead><tbody>${rows.map(([label,get])=>`<tr><th>${label}</th>${selected.map(v=>`<td>${esc(get(v))}</td>`).join('')}</tr>`).join('')}<tr><th>Negociar</th>${selected.map(v=>`<td><a class="btn btn-wa" data-wa data-message="${esc(messageFor(v))}">Falar sobre este veículo</a></td>`).join('')}</tr></tbody></table>`;bindWhatsApp(document.querySelector('#compare-table'));document.querySelector('#compare-modal').showModal()}

function imageList(v){return [...new Set([v.image,...(v.image_urls||[])].filter(Boolean))]}
function openVehicleEnhanced(v){if(!v)return;track('vehicle_view',{vehicle_id:v.id,vehicle:`${v.brand} ${v.model}`});const images=imageList(v),features=(v.features||[]);document.querySelector('#modal-content').innerHTML=`<div class="modal-layout premium-modal"><div class="modal-gallery"><img class="modal-photo" src="${esc(images[0])}" alt="${esc(v.brand)} ${esc(v.model)}"><div class="modal-thumbs">${images.map((src,i)=>`<button class="${i?'':'active'}" data-modal-image="${esc(src)}"><img src="${esc(src)}" alt="Foto ${i+1}"></button>`).join('')}</div><span class="gallery-count">1/${images.length}</span></div><div class="modal-info"><p class="eyebrow dark">${esc(({available:'Disponível',reserved:'Reservado',sold:'Vendido'})[v.status||'available'])} no estoque</p><h2>${esc(v.brand)} ${esc(v.model)}</h2><p>${esc(v.version||'Consulte a versão')}</p><div class="modal-specs"><div><b>Ano</b><br>${v.year}</div><div><b>Quilometragem</b><br>${Number(v.mileage||0).toLocaleString('pt-BR')} km</div><div><b>Câmbio</b><br>${esc(v.transmission||'Consulte')}</div><div><b>Combustível</b><br>${esc(v.fuel||'Consulte')}</div></div><p class="price">${money(v.price)}</p><div class="modal-actions"><a class="btn btn-wa" data-wa data-message="${esc(messageFor(v))}">Tenho interesse — WhatsApp</a><a href="vehicle.html?slug=${encodeURIComponent(v.slug||v.id)}" class="btn btn-dark">Ver detalhes completos</a><a href="#financiamento" class="details-btn" data-close-modal>Simular financiamento</a></div><div class="modal-features"><h3>Conheça este veículo</h3><p>${features.length?features.map(esc).join(' • '):'Consulte nossa equipe para conhecer os equipamentos cadastrados deste veículo.'}</p></div></div></div>`;document.querySelectorAll('[data-modal-image]').forEach((b,i)=>b.onclick=()=>{document.querySelector('.modal-photo').src=b.dataset.modalImage;document.querySelectorAll('[data-modal-image]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('.gallery-count').textContent=`${i+1}/${images.length}`});document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>modal.close());bindWhatsApp(document.querySelector('#modal-content'));modal.showModal()}

const journeyContent={
  buy:()=>`<div class="mode-layout"><div class="mode-copy"><p class="eyebrow">Comprar</p><h3>Encontre seu próximo veículo.</h3><p>Explore veículos disponíveis, filtre pelo que importa e fale diretamente sobre o veículo escolhido.</p><div class="mode-actions"><a href="#estoque" class="btn btn-light">Ver todo o estoque</a><a data-wa data-message="Olá! Preciso de ajuda para escolher meu próximo veículo." class="btn btn-ghost">Falar com vendedor</a></div></div><div class="mode-grid">${vehicles.filter(v=>v.featured).slice(0,3).map(v=>`<button data-detail="${v.id}"><small>${v.year} • ${esc(v.category||'Veículo')}</small><br>${esc(v.brand)} ${esc(v.model)}<br><span>${money(v.price)}</span></button>`).join('')}</div></div>`,
  sell:()=>`<div class="mode-layout"><div class="mode-copy"><p class="eyebrow">Vender</p><h3>Quer vender seu carro?</h3><div class="mode-steps"><article><b>01</b>Informe seu veículo</article><article><b>02</b>Envie os dados</article><article><b>03</b>Receba contato</article></div></div><form class="mode-form" data-mode-form="venda"><label>Marca<input required name="marca"></label><label>Modelo<input required name="modelo"></label><label>Ano<input required name="ano" type="number"></label><label>Quilometragem<input required name="quilometragem"></label><button class="btn btn-light">Quero vender meu carro</button></form></div>`,
  trade:()=>`<div class="mode-layout"><div class="mode-copy"><p class="eyebrow">Trocar</p><h3>Seu carro pode fazer parte do próximo negócio.</h3><p class="trade-equation">SEU CARRO <b>＋</b> LOJA DO PRETO <b>→</b> SEU PRÓXIMO CARRO</p></div><form class="mode-form" data-mode-form="troca"><label class="wide">Meu carro<input required name="carro"></label><label>Ano<input required name="ano" type="number"></label><label>Quilometragem<input required name="quilometragem"></label><label class="wide">Qual carro você procura?<input name="interesse"></label><button class="btn btn-light">Quero negociar uma troca</button></form></div>`,
  finance:()=>`<div class="mode-layout"><div class="mode-copy"><p class="eyebrow">Financiar</p><h3>Veja possibilidades para seu próximo carro.</h3><p>Uma estimativa inicial, sem promessa de aprovação.</p><strong class="mode-estimate" id="mode-estimate">R$ — /mês</strong></div><form class="mode-form" data-mode-form="financiamento"><label>Valor do veículo<input required name="valor" inputmode="numeric"></label><label>Entrada<input required name="entrada" inputmode="numeric"></label><label class="wide">Parcelas<select name="parcelas"><option>36</option><option>48</option><option>60</option></select></label><button class="btn btn-light">Continuar simulação</button></form></div>`
};
function setJourney(mode='buy'){const panel=document.querySelector('#journey-panel');panel.classList.add('changing');setTimeout(()=>{panel.innerHTML=journeyContent[mode]();panel.classList.remove('changing');document.querySelectorAll('.journey-tabs button').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',active)});bindWhatsApp(panel);bindDetails();panel.querySelectorAll('[data-mode-form]').forEach(form=>{form.addEventListener('input',()=>{if(form.dataset.modeForm==='financiamento'){const value=digits(form.valor.value),down=digits(form.entrada.value),months=+form.parcelas.value;document.querySelector('#mode-estimate').textContent=value?money(Math.max(0,value-down)/months*1.018)+' /mês':'R$ — /mês'}});form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));track(form.dataset.modeForm==='financiamento'?'financing_submit':'trade_in_submit',{source:'journey'});window.open(waLink(`Olá! Quero continuar uma solicitação de ${form.dataset.modeForm}.\n${Object.entries(data).map(([k,v])=>`${k}: ${v}`).join(' | ')}`),'_blank')}})},190)}

function renderAuxiliaryCollections(){const lifestyle=[...new Set(vehicles.flatMap(v=>v.lifestyle_categories||[]))];const defaults=lifestyle.length?lifestyle:['Primeiro carro','Para a família','Para trabalhar','Quero mais conforto','Quero um SUV','Quero trocar de carro'];document.querySelector('#lifestyle-rail').innerHTML=defaults.map((name,i)=>`<article class="moment-card" data-lifestyle="${esc(name)}" data-index="0${i+1}"><h3>${esc(name)}</h3><p>Ver veículos compatíveis</p></article>`).join('');document.querySelectorAll('[data-lifestyle]').forEach(el=>el.onclick=()=>{filters.intent=el.dataset.lifestyle;track('filter_used',{filter:'lifestyle',value:filters.intent});renderInventory();document.querySelector('#estoque').scrollIntoView()});const arrivals=vehicles.filter(v=>v.newly_arrived).slice(0,8);document.querySelector('#arrivals-rail').innerHTML=(arrivals.length?arrivals:vehicles.slice(0,4)).map(card).join('');bindWhatsApp(document.querySelector('#arrivals-rail'));bindDetails();bindCardActions()}

const dealState={step:0,vehicle:null,trade:null,finance:null};function renderDeal(){const root=document.querySelector('#deal-builder'),progress=document.querySelectorAll('.deal-progress span');progress.forEach((x,i)=>x.classList.toggle('active',i<=dealState.step));if(dealState.step===0)root.innerHTML=`<h3>Qual veículo chamou sua atenção?</h3><div class="deal-options">${vehicles.slice(0,5).map(v=>`<button data-deal="vehicle" data-value="${v.id}">${esc(v.brand)} ${esc(v.model)} ${v.year}</button>`).join('')}<button data-deal="vehicle" data-value="Ainda não escolhi">Ainda não escolhi</button></div>`;if(dealState.step===1)root.innerHTML=`<h3>Vai dar carro na troca?</h3><div class="deal-options"><button data-deal="trade" data-value="Sim">Sim, tenho um veículo</button><button data-deal="trade" data-value="Não">Não</button></div><button class="deal-back">← Voltar</button>`;if(dealState.step===2)root.innerHTML=`<h3>Pretende financiar?</h3><div class="deal-options"><button data-deal="finance" data-value="Sim">Sim, quero consultar</button><button data-deal="finance" data-value="Não">Não</button></div><button class="deal-back">← Voltar</button>`;if(dealState.step===3){const v=vehicles.find(x=>String(x.id)===String(dealState.vehicle));const label=v?`${v.brand} ${v.model} ${v.year}`:'um veículo';root.innerHTML=`<h3>Vamos continuar pelo WhatsApp.</h3><p>Seu contexto será enviado para a equipe, sem formulário repetido.</p><a class="btn btn-wa" data-wa data-message="Olá! Tenho interesse em ${esc(label)}. ${dealState.trade==='Sim'?'Tenho um veículo para troca.':'Não tenho veículo para troca.'} ${dealState.finance==='Sim'?'Gostaria de consultar financiamento.':'Não pretendo financiar neste momento.'}">Continuar no WhatsApp</a><button class="deal-back">← Revisar respostas</button>`;bindWhatsApp(root)}root.querySelectorAll('[data-deal]').forEach(b=>b.onclick=()=>{dealState[b.dataset.deal]=b.dataset.value;dealState.step++;renderDeal()});root.querySelector('.deal-back')?.addEventListener('click',()=>{dealState.step=Math.max(0,dealState.step-1);renderDeal()})}

document.querySelectorAll('.journey-tabs button').forEach(b=>b.onclick=()=>setJourney(b.dataset.mode));document.querySelectorAll('[data-mode-link]').forEach(a=>a.onclick=()=>setJourney(a.dataset.modeLink));
document.querySelector('#natural-search-button').onclick=()=>{filters.query=document.querySelector('#natural-search').value.trim();track('search_used',{query:filters.query});renderInventory();document.querySelector('#estoque').scrollIntoView()};document.querySelector('#natural-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();document.querySelector('#natural-search-button').click()}});
document.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-intent]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filters.intent=b.dataset.intent;track('filter_used',{filter:'intent',value:filters.intent});renderInventory();document.querySelector('#estoque').scrollIntoView()});
const showFavorites=()=>{filters.favorite=!filters.favorite;renderInventory();document.querySelector('#estoque').scrollIntoView()};document.querySelector('#show-favorites').onclick=showFavorites;document.querySelector('#nav-favorites').onclick=showFavorites;document.querySelector('#mobile-favorites').onclick=showFavorites;
document.querySelector('#mobile-filter').onclick=()=>{document.querySelector('.filter-grid').classList.add('open');document.querySelector('.filter-toggle').setAttribute('aria-expanded','true');document.querySelector('.quick').scrollIntoView()};document.querySelector('#open-compare').onclick=openCompare;document.querySelector('#close-compare').onclick=()=>{storageWrite('ldp-compare',[]);renderCompareTray();renderInventory()};document.querySelector('.compare-close').onclick=()=>document.querySelector('#compare-modal').close();
document.querySelectorAll('[data-carousel]').forEach(b=>b.onclick=()=>document.querySelector(`#${b.dataset.carousel}-rail`).scrollBy({left:Number(b.dataset.dir)*360,behavior:'smooth'}));
document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#nav').classList.remove('open')));
window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight,percent=max?scrollY/max*100:0;document.querySelector('.scroll-progress span').style.width=`${percent}%`;document.querySelector('.header').classList.toggle('compact',scrollY>80)},{passive:true});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('main>section:not(.hero),.vehicle-card').forEach(el=>{el.classList.add('reveal-on-scroll');revealObserver.observe(el)});
document.addEventListener('click',e=>{const wa=e.target.closest('[data-wa]');if(wa)track('whatsapp_click',{message:wa.dataset.message||'',path:location.pathname})});
setJourney('buy');renderDeal();updateFavoriteUI();renderCompareTray();renderAuxiliaryCollections();



