(()=>{
  const db=window.supabaseClient,grid=document.querySelector('#vehicle-grid'),mode=document.body.dataset.catalog||'stock';
  const params=new URLSearchParams(location.search);const state={page:0,size:12,rows:[],filters:{},category:params.get('categoria')||'all',type:params.get('tipo')||'all'};
  const money=n=>n==null?'Consulte':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
  const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const favs=()=>JSON.parse(localStorage.getItem('ldp-favorites')||'[]');
  let compare=[];
  function query(){
    let q=db.from('vehicles').select('*',{count:'exact'}).eq('active',true).range(state.page*state.size,(state.page+1)*state.size-1);
    if(mode==='highlights')q=q.or('featured.eq.true,newly_arrived.eq.true,highlight_category.not.is.null').order('highlight_position',{ascending:true,nullsFirst:false});
    else q=q.order('created_at',{ascending:false});
    if(state.type!=='all')q=q.eq('vehicle_type',state.type);if(params.get('filtro')==='recentes')q=q.eq('newly_arrived',true);if(params.get('favoritos')==='1'){const ids=favs();q=ids.length?q.in('id',ids):q.eq('id','00000000-0000-0000-0000-000000000000')}
    const f=state.filters;if(f.search){const t=`%${f.search}%`;q=q.or(`brand.ilike.${t},model.ilike.${t},version.ilike.${t},category.ilike.${t},body_type.ilike.${t}`)}
    if(f.vehicle_type)q=q.eq('vehicle_type',f.vehicle_type);['brand','model','transmission','fuel','color','body_type'].forEach(k=>{if(f[k])q=q.ilike(k,`%${f[k]}%`)});
    if(state.category!=='all'){if(state.category==='new')q=q.eq('newly_arrived',true);else if(state.category==='premium')q=q.or('highlight_category.ilike.%premium%,highlight_category.ilike.%luxo%');else q=q.or(`category.ilike.%${state.category}%,body_type.ilike.%${state.category}%`)}
    if(f.year_min)q=q.gte('year',f.year_min);if(f.year_max)q=q.lte('year',f.year_max);if(f.price_min)q=q.gte('price',f.price_min);if(f.price_max)q=q.lte('price',f.price_max);if(f.mileage_max)q=q.lte('mileage',f.mileage_max);return q;
  }
  function card(v){const f=favs().includes(v.id),kind=(v.vehicle_type||'car')==='motorcycle'?'Moto':'Carro',slug=v.slug||v.id,img=v.image_url||v.image_urls?.[0]||'assets/hero-showroom.jpg';return `<article class="catalog-card"><div class="card-media"><a href="/vehicle?slug=${encodeURIComponent(slug)}"><img loading="lazy" src="${safe(img)}" alt="${safe(v.brand)} ${safe(v.model)}"></a><div class="card-badges">${v.featured?'<span>Destaque</span>':''}${v.newly_arrived?'<span>Novidade</span>':''}${v.status==='sold'?'<span>Vendido</span>':''}</div><button class="card-fav ${f?'active':''}" data-fav="${safe(v.id)}" aria-label="Favoritar"><svg class="card-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.7Z"/></svg></button></div><div class="card-body"><span class="card-kind">${kind}</span><h3>${safe(v.brand)} ${safe(v.model)}</h3><p>${safe(v.version||'')}</p><div class="card-specs"><span>${safe(v.year||'—')}</span><span>${v.mileage!=null?Number(v.mileage).toLocaleString('pt-BR')+' km':'—'}</span><span>${safe(v.transmission||'—')}</span></div><div class="card-price"><strong>${money(v.price)}</strong><a href="/vehicle?slug=${encodeURIComponent(slug)}">Ver detalhes</a></div><button class="card-compare" data-compare="${safe(v.id)}">Comparar</button></div></article>`}
  async function load(reset=false){if(reset){state.page=0;state.rows=[];grid.innerHTML=''};grid.classList.add('loading');document.querySelector('#catalog-status').textContent='Carregando veículos…';if(!db){grid.classList.remove('loading');grid.innerHTML='<div class="empty-catalog">O catálogo está temporariamente indisponível. Fale com nossa equipe.</div>';document.querySelector('#catalog-status').textContent='Catálogo indisponível';document.querySelector('#load-more').hidden=true;return}const {data,count,error}=await query();grid.classList.remove('loading');if(error){grid.innerHTML='<div class="empty-catalog">Não foi possível carregar o estoque agora.</div>';return}state.rows.push(...(data||[]));
    if(mode==='highlights'&&state.page===0&&data?.length){const lead=data[0];document.querySelector('#editorial-lead').innerHTML=`<img src="${safe(lead.image_url||lead.image_urls?.[0])}" alt="${safe(lead.brand)} ${safe(lead.model)}"><div class="editorial-copy"><p class="eyebrow">${safe(lead.highlight_category||'Escolha da Loja')}</p><h2>${safe(lead.brand)} ${safe(lead.model)}</h2><p>${safe(lead.description||lead.version||'Uma seleção especial do nosso estoque.')}</p><strong>${money(lead.price)}</strong><a class="portal-btn light" href="/vehicle?slug=${encodeURIComponent(lead.slug||lead.id)}">Conhecer este veículo</a></div>`;grid.innerHTML=data.slice(1).map(card).join('')}else grid.insertAdjacentHTML('beforeend',(data||[]).map(card).join(''));
    if(!state.rows.length)grid.innerHTML='<div class="empty-catalog"><h3>Nenhum veículo encontrado com esses filtros.</h3><p>Ajuste sua busca para ver outras opções disponíveis.</p><button class="portal-btn dark" data-empty-clear>Limpar filtros</button></div>';document.querySelector('#catalog-status').textContent=`${count||0} veículo${count===1?'':'s'} encontrado${count===1?'':'s'}`;const more=document.querySelector('#load-more');if(more)more.hidden=state.rows.length>=(count||0)||!data?.length;grid.querySelector('[data-empty-clear]')?.addEventListener('click',()=>document.querySelector('#filter-clear')?.click());bindCards();
  }
  function bindCards(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{let a=favs(),id=b.dataset.fav;a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('ldp-favorites',JSON.stringify(a));b.classList.toggle('active');document.querySelectorAll('[data-favorite-count]').forEach(x=>x.textContent=a.length)});document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const v=state.rows.find(x=>String(x.id)===b.dataset.compare);if(!v)return;if(compare.some(x=>x.id===v.id))compare=compare.filter(x=>x.id!==v.id);else if(compare.length<3)compare.push(v);const tray=document.querySelector('#compare-tray');tray.hidden=!compare.length;tray.querySelector('span').textContent=`${compare.length}/3 selecionados para comparar`})}
  document.querySelector('#load-more')?.addEventListener('click',()=>{state.page++;load()});document.querySelector('.filter-toggle')?.addEventListener('click',()=>document.querySelector('.filters')?.classList.toggle('open'));
  let debounce;document.querySelectorAll('#catalog-search,.filters input,.filters select').forEach(el=>el.addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(()=>{const form=document.querySelector('#filters'),fd=new FormData(form);state.filters=Object.fromEntries(fd.entries());state.filters.search=document.querySelector('#catalog-search')?.value.trim();load(true)},280)}));
  document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.category;state.type=b.dataset.type||'all';load(true)}));document.querySelector('#filter-clear')?.addEventListener('click',()=>{document.querySelector('#filters').reset();document.querySelector('#catalog-search').value='';state.filters={};state.category='all';state.type='all';load(true)});
  async function hydrateChips(){if(!db)return;const{data}=await db.from('vehicles').select('vehicle_type,category,body_type,highlight_category,newly_arrived').eq('active',true).neq('status','sold');const rows=data||[],types=new Set(rows.map(v=>v.vehicle_type||'car')),cats=rows.flatMap(v=>[v.category,v.body_type]).filter(Boolean).map(v=>String(v).toLowerCase());document.querySelectorAll('[data-type]').forEach(b=>{if(b.dataset.type!=='all')b.hidden=!types.has(b.dataset.type)});document.querySelectorAll('[data-category]').forEach(b=>{const key=String(b.dataset.category||'').toLowerCase();if(['all'].includes(key)||b.dataset.type)return;if(key==='premium')b.hidden=!rows.some(v=>/premium|luxo/i.test(v.highlight_category||''));else if(key==='new')b.hidden=!rows.some(v=>v.newly_arrived);else b.hidden=!cats.some(v=>v.includes(key.toLowerCase()))})}
  hydrateChips();load();
})();




