(()=>{
  if(document.body.closest('.admin')||location.pathname.startsWith('/admin'))return;
  const db=window.supabaseClient,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money=value=>window.LDP_CURRENCY.format(value,'Consulte o valor');
  const ref=value=>value?`REF ${String(value).padStart(3,'0')}`:'';
  const track=(event,detail={})=>{window.dataLayer?.push({event,...detail});dispatchEvent(new CustomEvent('ldp:conversion',{detail:{event,...detail}}))};
  document.addEventListener('click',event=>{const link=event.target.closest('a,button');if(!link)return;if(link.matches('[data-wa],[data-catalog-wa],[data-context]'))track('whatsapp_click',{location:location.pathname});else if(link.closest('.catalog-card,.vehicle-card'))track('vehicle_click',{location:location.pathname});else if(link.closest('.hero-actions'))track('hero_cta',{label:link.textContent.trim()})},{passive:true});
  function motion(){if(reduce)return;const hero=document.querySelector('.hero');if(hero){hero.addEventListener('pointermove',event=>{const x=(event.clientX/innerWidth-.5)*12,y=(event.clientY/innerHeight-.5)*8;hero.style.setProperty('--hero-x',`${x}px`);hero.style.setProperty('--hero-y',`${y}px`)},{passive:true});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--hero-x','0px');hero.style.setProperty('--hero-y','0px')},{passive:true})}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('main>section,.catalog-card,.vehicle-card').forEach(element=>{element.classList.add('experience-reveal');observer.observe(element)})}
  function enhanceCards(vehicles){const map=new Map(vehicles.map(v=>[String(v.id),v]));document.querySelectorAll('.vehicle-card').forEach(card=>{const id=card.querySelector('[data-favorite]')?.dataset.favorite,vehicle=map.get(String(id));if(!vehicle||card.dataset.experience)return;card.dataset.experience='true';card.dataset.reference=vehicle.reference||'';if(vehicle.reference){const badge=document.createElement('span');badge.className='experience-reference';badge.textContent=ref(vehicle.reference);card.querySelector('.vehicle-photo')?.append(badge)}const cue=document.createElement('span');cue.className='vehicle-hover-cue';cue.textContent='Ver detalhes';card.querySelector('.vehicle-photo')?.append(cue)})}
  function tile(vehicle){const image=vehicle.image_url||vehicle.image_urls?.[0]||'/assets/hero-showroom.png';return `<a class="sold-tile" href="/veiculos/${encodeURIComponent(vehicle.slug||vehicle.id)}"><img loading="lazy" decoding="async" src="${safe(image)}" alt="${safe(vehicle.brand)} ${safe(vehicle.model)}"><span>Vendido</span><div><small>${ref(vehicle.reference)}</small><strong>${safe(vehicle.brand)} ${safe(vehicle.model)}</strong><p>${safe(vehicle.year||'')} · ${safe(vehicle.version||'')}</p></div></a>`}
  function buildHome(vehicles,settings){if(!document.body.classList.contains('home-portal'))return;const available=vehicles.filter(v=>v.status!=='sold'),sold=vehicles.filter(v=>v.status==='sold');const categories=[...new Set(available.map(v=>v.body_type||v.category).filter(Boolean))].slice(0,6);const ranges=[{label:'Até R$ 50 mil',min:0,max:50000},{label:'R$ 50–80 mil',min:50000,max:80000},{label:'R$ 80–120 mil',min:80000,max:120000},{label:'Acima de R$ 120 mil',min:120000,max:null}].filter(range=>available.some(v=>Number(v.price)>range.min&&(!range.max||Number(v.price)<=range.max)));
    const explorer=document.createElement('section');explorer.className='experience-section explorer-section';explorer.innerHTML=`<div class="container"><div class="experience-heading"><div><p class="eyebrow">Encontre do seu jeito</p><h2>O estoque começa pela sua escolha.</h2></div><a href="/estoque">Ver estoque completo <span>→</span></a></div><div class="explorer-layout"><form action="/estoque" class="reference-quick-search"><label for="home-vehicle-search">Busca rápida</label><div><input id="home-vehicle-search" name="busca" placeholder="Modelo, marca ou REF 025"><button type="submit">Buscar</button></div></form>${categories.length?`<div class="explorer-links"><small>Por categoria</small>${categories.map(c=>`<a href="/estoque?categoria=${encodeURIComponent(c)}">${safe(c)} <span>→</span></a>`).join('')}</div>`:''}${ranges.length?`<div class="explorer-links"><small>Por faixa de preço</small>${ranges.map(r=>`<a href="/estoque?preco_min=${r.min}&preco_max=${r.max||''}">${r.label} <span>→</span></a>`).join('')}</div>`:''}</div></div>`;document.querySelector('.journey')?.insertAdjacentElement('afterend',explorer);
    const process=document.createElement('section');process.className='experience-section process-section';process.innerHTML='<div class="container"><p class="eyebrow">Do interesse à chave</p><h2>Comprar seu carro pode ser simples.</h2><div class="purchase-steps"><article><b>01</b><h3>Escolha</h3><p>Explore o estoque real e abra todos os detalhes.</p></article><article><b>02</b><h3>Converse</h3><p>Fale com a equipe já identificando a referência.</p></article><article><b>03</b><h3>Visite</h3><p>Combine os próximos passos diretamente com a loja.</p></article><article><b>04</b><h3>Negocie</h3><p>Avance com informação clara e atendimento humano.</p></article></div></div>';document.querySelector('#destaques')?.insertAdjacentElement('afterend',process);
    if(sold.length){const soldSection=document.createElement('section');soldSection.className='experience-section sold-section';soldSection.innerHTML=`<div class="container"><div class="experience-heading"><div><p class="eyebrow">Estoque em movimento</p><h2>Já encontraram um novo dono.</h2></div></div><div class="sold-grid">${sold.slice(0,4).map(tile).join('')}</div></div>`;process.insertAdjacentElement('afterend',soldSection)}
    const footer=document.querySelector('footer');if(footer){const contact=document.createElement('section');contact.className='contact-stripe';contact.innerHTML=`<div class="container"><div><p class="eyebrow">Atendimento direto</p><h2>Encontrou o carro certo?</h2><p>${safe(settings.business_hours||'Fale com a equipe e combine os próximos passos.')}</p></div><a class="btn btn-wa" data-wa data-message="Olá! Vi o site da Loja do Preto e quero falar sobre um veículo.">Falar no WhatsApp <span>→</span></a></div>`;footer.before(contact)}}
  async function init(){let vehicles=[],settings={};if(db){const[result,config]=await Promise.all([db.from('vehicles').select('*').eq('active',true).order('created_at',{ascending:false}),db.from('store_settings').select('*').eq('id',1).maybeSingle()]);vehicles=result.data||[];settings=config.data||{}}enhanceCards(vehicles);buildHome(vehicles,settings);motion();const observer=new MutationObserver(()=>enhanceCards(vehicles));observer.observe(document.body,{childList:true,subtree:true})}
  init();
})();
