(()=>{const icon=name=>({chevron:'<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 9.5 5 5 5-5"/></svg>',search:'<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',heart:'<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.7Z"/></svg>',whatsapp:'<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.4-4.7a8.5 8.5 0 1 1 16.1-4.1Z"/><path d="M8.2 7.8c.2-.5.4-.5.7-.5h.4c.2 0 .4.1.5.4l.8 2c.1.3.1.5-.1.7l-.6.7c-.2.2-.1.4 0 .6.6 1 1.4 1.8 2.4 2.4.2.1.4.2.6 0l.8-1c.2-.2.4-.3.7-.2l2 .9c.3.1.4.3.4.5 0 .3-.2 1.4-.8 1.9-.5.5-1.3.8-2.1.7-1.3-.2-3.1-.8-5-2.5-1.4-1.3-2.4-2.9-2.7-4.2-.3-1.1 0-1.9.4-2.4Z"/></svg>'}[name]||'' );if(!document.querySelector('link[href$="navigation.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/navigation.css';document.head.append(l)}
  const header=document.querySelector('body > header');if(!header)return;
  const path=location.pathname.replace(/\.html$/,'').replace(/\/$/,'')||'/';
  const page=path.startsWith('/estoque/')?'vehicle':path==='/estoque'?'stock':path==='/destaques'?'highlights':path==='/venda-seu-carro'||path==='/venda'?'sell':path==='/financiamento'?'finance':path==='/nossa-historia'||path==='/historia'?'history':path==='/contato'?'contact':'home';
  const active=key=>key===page||key==='buy'&&['stock','vehicle'].includes(page);
  header.className='portal-header site-header';header.innerHTML=`<a class="portal-brand" href="/" aria-label="Loja do Preto — página inicial"><img class="portal-logo" src="/assets/logo-clean.png" alt="Loja do Preto"></a><nav class="portal-nav" id="nav" aria-label="Navegação principal"><div class="nav-group ${active('buy')?'active':''}"><button class="nav-trigger" aria-expanded="false" aria-haspopup="true">Comprar <span class="nav-chevron">${icon('chevron')}</span></button><div class="nav-dropdown"><a href="/estoque"><b>Ver todo o estoque</b><small>Todos os veículos disponíveis.</small></a><a href="/destaques"><b>Destaques</b><small>Uma seleção especial da Loja do Preto.</small></a><a href="/estoque?filtro=recentes"><b>Recém-chegados</b><small>Os veículos que acabaram de entrar.</small></a><div class="nav-categories" data-real-categories></div></div></div><a class="nav-direct ${active('highlights')?'active':''}" href="/destaques">Destaques</a><div class="nav-group ${active('sell')?'active':''}"><button class="nav-trigger" aria-expanded="false" aria-haspopup="true">Vender <span class="nav-chevron">${icon('chevron')}</span></button><div class="nav-dropdown"><a href="/venda-seu-carro#avaliacao"><b>Venda seu carro</b><small>Envie os dados para avaliação.</small></a><a href="/venda-seu-carro?tipo=troca#avaliacao"><b>Dar carro na troca</b><small>Use seu veículo em uma negociação.</small></a><a href="/venda-seu-carro#avaliacao"><b>Avaliar meu veículo</b><small>Solicite uma avaliação.</small></a></div></div><div class="nav-group ${active('finance')?'active':''}"><button class="nav-trigger" aria-expanded="false" aria-haspopup="true">Financiar <span class="nav-chevron">${icon('chevron')}</span></button><div class="nav-dropdown"><a href="/financiamento#simulacao"><b>Simular financiamento</b></a><a href="/financiamento#como-funciona"><b>Como funciona</b></a><a data-nav-wa href="#"><b>Falar sobre financiamento</b><small>Continue diretamente no WhatsApp.</small></a></div></div><a class="nav-direct ${active('history')?'active':''}" href="/nossa-historia">Nossa História</a><a class="nav-direct ${active('contact')?'active':''}" href="/contato">Contato</a><a class="mobile-wa" data-nav-wa href="#">Falar no WhatsApp</a></nav><div class="portal-actions"><button class="icon-button" data-open-global-search aria-label="Pesquisar veículos">${icon('search')}</button><a class="icon-button favorite-link" href="/estoque?favoritos=1" aria-label="Favoritos">${icon('heart')} <b data-favorite-count>0</b></a><a class="portal-btn green desktop-wa" data-nav-wa href="#">${icon('whatsapp')}<span>Falar com vendedor</span></a><button class="portal-menu menu" aria-label="Abrir menu" aria-expanded="false" aria-controls="nav"><span></span><span></span><span></span></button></div>`;
  header.querySelectorAll('[data-nav-wa]').forEach(a=>a.href='/contato');let settings={};const wa=message=>`https://wa.me/${String(settings.whatsapp||'').replace(/\D/g,'')}?text=${encodeURIComponent(message)}`;
  async function hydrate(){if(window.supabaseClient){const[{data:s},{data:v}]=await Promise.all([window.supabaseClient.from('store_settings').select('whatsapp').limit(1).maybeSingle(),window.supabaseClient.from('vehicles').select('vehicle_type,category,body_type,highlight_category').eq('active',true).neq('status','sold')]);settings=s||{};const rows=v||[],root=document.querySelector('[data-real-categories]'),groups=[];const section=(type,label,allLabel)=>{const own=rows.filter(x=>(x.vehicle_type||'car')===type);if(!own.length)return;const cats=[...new Set(own.flatMap(x=>[x.body_type,x.category]).filter(Boolean))];groups.push(`<section><p>${label}</p><a href="/estoque?tipo=${type}"><b>${allLabel}</b></a>${cats.map(x=>`<a href="/estoque?tipo=${type}&categoria=${encodeURIComponent(x)}"><b>${x}</b></a>`).join('')}</section>`)};section('car','Carros','Todos os carros');section('motorcycle','Motos','Todas as motos');root.innerHTML=groups.join('')}document.querySelectorAll('[data-nav-wa]').forEach(a=>{a.href=wa(a.closest('.nav-dropdown')?'Olá! Gostaria de falar sobre financiamento.':'Olá! Gostaria de falar com um vendedor da Loja do Preto.');a.target='_blank';a.rel='noopener'})}
  const nav=header.querySelector('#nav'),menu=header.querySelector('.portal-menu');const closeAll=()=>{header.querySelectorAll('.nav-group.open').forEach(g=>g.classList.remove('open'));header.querySelectorAll('.nav-trigger').forEach(b=>b.setAttribute('aria-expanded','false'))};const closeMenu=({focus=false}={})=>{closeAll();nav.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');if(focus)menu.focus()};menu.addEventListener('click',()=>{const open=!nav.classList.contains('open');if(open){nav.classList.add('open');menu.classList.add('open');menu.setAttribute('aria-expanded','true');document.body.classList.add('menu-open')}else closeMenu()});header.querySelectorAll('.nav-trigger').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const group=btn.closest('.nav-group'),open=!group.classList.contains('open');closeAll();group.classList.toggle('open',open);btn.setAttribute('aria-expanded',String(open))}));header.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));document.addEventListener('click',e=>{if(!header.contains(e.target))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu({focus:true})});addEventListener('resize',()=>{if(innerWidth>1120)closeMenu()},{passive:true});addEventListener('scroll',()=>header.classList.toggle('compact',scrollY>40),{passive:true});header.querySelector('[data-favorite-count]').textContent=JSON.parse(localStorage.getItem('ldp-favorites')||'[]').length;header.querySelector('[data-open-global-search]').addEventListener('click',()=>{const d=document.querySelector('#global-search');if(d)d.showModal();else location.href='/estoque'});hydrate();
})();







