window.SUPABASE_CONFIG={
  url:'https://mkvkoeuaopgoobrszuzy.supabase.co',
  publishableKey:'sb_publishable_zZnHgX_jYjCoIzdXFldJnA_9f8cXqe0'
};
window.LDP_CURRENCY=Object.freeze({currency:'BRL',locale:'pt-BR',format(value,fallback='Consulte o valor'){const number=Number(value);return Number.isFinite(number)&&number>0?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2}).format(number):fallback},number(value){const number=Number(value);return Number.isFinite(number)&&number>=0?number:null}});
window.LDP_WHATSAPP=Object.freeze({official:'https://wa.me/message/UQTIE7VJAIOXP1',defaultMessage:'Olá! Vim pelo site da Loja do Preto e gostaria de mais informações.',vehicleTemplate:'Olá! Tenho interesse no {veiculo} {ano}, anunciado por {preco}. Gostaria de mais informações.\n\nAnúncio: {link}',url(value='',message=''){const input=String(value||'').trim(),valid=/^https:\/\/wa\.me\/message\/[A-Za-z0-9]+\/?(?:\?.*)?$/i.test(input),base=valid?input:this.official;if(!message)return base;const url=new URL(base);url.searchParams.set('text',String(message));return url.toString()},vehicleMessage(vehicle={},template=''){const clean=value=>String(value??'').trim(),name=[vehicle.brand,vehicle.model,vehicle.version].map(clean).filter(Boolean).join(' '),price=window.LDP_CURRENCY.format(vehicle.price,''),link=clean(vehicle.link)||(vehicle.slug||vehicle.id?new URL(`/veiculos/${encodeURIComponent(vehicle.slug||vehicle.id)}`,location.origin).href:location.href),values={veiculo:name,marca:clean(vehicle.brand),modelo:clean(vehicle.model),ano:clean(vehicle.year),preco:price,link};let source=String(template||this.vehicleTemplate);if(!price)source=source.replace(/,?\s*anunciado por\s*\{preco\}/i,'');let message=source.replace(/\{(veiculo|marca|modelo|ano|preco|link)\}/g,(_,key)=>values[key]);message=message.replace(/[ \t]+([,.])/g,'$1').replace(/ {2,}/g,' ').replace(/\n{3,}/g,'\n\n').trim();return message||`Olá! Tenho interesse no ${name||'veículo anunciado'} e gostaria de mais informações.`}});
if(!document.querySelector('link[href$="price.css"]')){const priceStyles=document.createElement('link');priceStyles.rel='stylesheet';priceStyles.href='/price.css';document.head.append(priceStyles)}
if(!document.querySelector('script[src$="business-links.js"]')){const businessLinks=document.createElement('script');businessLinks.src='/business-links.js';businessLinks.defer=true;document.head.append(businessLinks)}
if(!document.querySelector('script[src$="whatsapp-runtime.js"]')){const whatsappRuntime=document.createElement('script');whatsappRuntime.src='/whatsapp-runtime.js';whatsappRuntime.defer=true;document.head.append(whatsappRuntime)}
if(window.supabase&&!window.SUPABASE_CONFIG.url.startsWith('[')){
  window.supabaseClient=window.supabase.createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.publishableKey);
}

