if(!document.querySelector('link[href$="motion.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/motion.css';document.head.append(l)}if(!document.querySelector('script[src$="navigation.js"]')){const s=document.createElement('script');s.src='/navigation.js';document.head.append(s)}if(!document.querySelector('script[src$="motion.js"]')){const s=document.createElement('script');s.src='/motion.js';document.head.append(s)}
const client = window.supabaseClient;
const requested = new URLSearchParams(location.search).get('slug') || location.pathname.split('/').filter(Boolean).pop();
const money = n => window.LDP_CURRENCY.format(n,'Consulte o valor');
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const wa = (message, number='') => `https://wa.me/${String(number).replace(/\D/g,'')}?text=${encodeURIComponent(message)}`;
let images = [], imageIndex = 0, vehicle, settings = {};
function showImage(next) { imageIndex=(next+images.length)%images.length; document.querySelector('#main-vehicle-image').src=images[imageIndex]; document.querySelector('#gallery-index').textContent=`${imageIndex+1}/${images.length}`; document.querySelectorAll('.vehicle-thumbs button').forEach((b,i)=>b.classList.toggle('active',i===imageIndex)); }
function contactMessage(context='mais informações') { return `Olá! Estou vendo o ${vehicle.brand} ${vehicle.model} ${vehicle.version||''} ${vehicle.year} no site da Loja do Preto e gostaria de consultar ${context}.`; }
function setLinks() { document.querySelectorAll('[data-context]').forEach(a=>{a.href=wa(contactMessage(a.dataset.context),vehicle.whatsapp_number||settings.whatsapp);a.target='_blank';a.rel='noopener'});const header=document.querySelector('#header-contact');if(header){header.href=wa(contactMessage(),vehicle.whatsapp_number||settings.whatsapp);header.target='_blank'} }
function render() {
  images=[...new Set([vehicle.image_url,...(vehicle.image_urls||[])].filter(Boolean))]; if(!images.length)images=['/assets/hero-showroom.png'];
  const features=vehicle.features||[],status=({available:'Disponível',reserved:'Reservado',preparing:'Em preparação',sold:'Vendido'})[vehicle.status||'available'],kindLabel=(vehicle.vehicle_type||'car')==='motorcycle'?'Moto':'Carro';
  const fit=[kindLabel,vehicle.body_type,vehicle.category,vehicle.transmission,`Modelo ${vehicle.year}`,vehicle.fuel,...(vehicle.tags||[])].filter(Boolean).slice(0,6);
  document.title=`${vehicle.brand} ${vehicle.model} ${vehicle.version||''} ${vehicle.year} | Loja do Preto`;
  document.querySelector('meta[name="description"]').content=`Conheça o ${vehicle.brand} ${vehicle.model} ${vehicle.version||''} ${vehicle.year} disponível na Loja do Preto.`;
  document.querySelector('#vehicle-content').innerHTML=`<div class="vehicle-shell"><section class="vehicle-top"><div><div class="vehicle-gallery-main"><img id="main-vehicle-image" src="${esc(images[0])}" alt="${esc(vehicle.brand)} ${esc(vehicle.model)}"><div class="vehicle-gallery-controls"><button id="prev-image" aria-label="Foto anterior"><svg class="vehicle-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg></button><span id="gallery-index">1/${images.length}</span><button id="next-image" aria-label="Próxima foto"><svg class="vehicle-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></button></div></div><div class="vehicle-thumbs">${images.map((src,i)=>`<button class="${i?'':'active'}" data-image="${i}"><img src="${esc(src)}" alt="Foto ${i+1}"></button>`).join('')}</div></div><aside class="negotiation-panel"><p class="eyebrow dark">${status}</p><h1>${esc(vehicle.brand)} ${esc(vehicle.model)}</h1><p class="vehicle-version">${esc(vehicle.version||'Versão a consultar')}</p><div class="vehicle-key-specs"><div><b>Ano</b><br>${vehicle.year}</div><div><b>KM</b><br>${Number(vehicle.mileage||0).toLocaleString('pt-BR')}</div><div><b>Câmbio</b><br>${esc(vehicle.transmission||'Consulte')}</div><div><b>Combustível</b><br>${esc(vehicle.fuel||'Consulte')}</div></div><p class="price">${money(vehicle.price)}</p><div class="negotiation-actions"><a class="btn btn-wa" data-context="as condições de negociação">Tenho interesse</a><a class="btn btn-dark" data-context="as possibilidades de financiamento">Simular financiamento</a><a class="details-btn" data-context="usar meu veículo na troca">Usar meu carro na troca</a></div></aside></section><section class="vehicle-knowledge"><p class="eyebrow dark">Conheça o veículo</p><h2>Informação organizada para decidir melhor.</h2><div class="knowledge-tabs"><button class="active" data-tab="overview">Visão geral</button><button data-tab="equipment">Equipamentos</button><button data-tab="details">Detalhes</button></div><div class="knowledge-panel" id="knowledge-panel"></div></section><section class="vehicle-fit"><p class="eyebrow">Este veículo é para você?</p><h2>Pode combinar com quem procura:</h2><ul>${fit.map(x=>`<li>✓ ${esc(x)}</li>`).join('')}</ul></section></div>`;
  const panels={overview:vehicle.description||`Conheça os dados cadastrados deste ${vehicle.brand} ${vehicle.model} e fale com nossa equipe para confirmar todos os detalhes.`,equipment:features.length?`<ul class="equipment-list">${features.map(x=>`<li>✓ ${esc(x)}</li>`).join('')}</ul>`:'Nenhum equipamento foi cadastrado. Consulte a equipe para obter informações reais.',details:`Ano ${vehicle.year} • ${Number(vehicle.mileage||0).toLocaleString('pt-BR')} km • ${esc(vehicle.transmission||'Câmbio a consultar')} • ${esc(vehicle.fuel||'Combustível a consultar')} • ${esc(vehicle.color||'Cor a consultar')}`};
  const showPanel=name=>{document.querySelector('#knowledge-panel').innerHTML=panels[name];document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name))};
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showPanel(b.dataset.tab)); document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>showImage(+b.dataset.image)); document.querySelector('#prev-image').onclick=()=>showImage(imageIndex-1); document.querySelector('#next-image').onclick=()=>showImage(imageIndex+1); showPanel('overview');
  document.querySelector('#sticky-name').textContent=`${vehicle.brand} ${vehicle.model} ${vehicle.year}`; document.querySelector('#sticky-price').textContent=money(vehicle.price); document.querySelector('#sticky-wa').dataset.context='as condições de negociação'; document.querySelector('#vehicle-sticky').hidden=false; setLinks();
}
async function init(){try{if(!client)throw new Error('Catálogo indisponível');const isUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(requested);const vehicleQuery=isUuid?client.from('vehicles').select('*').eq('id',requested).maybeSingle():client.from('vehicles').select('*').eq('slug',requested).maybeSingle();const[{data:v,error},{data:s}]=await Promise.all([vehicleQuery,client.from('store_settings').select('*').eq('id',1).maybeSingle()]);if(error||!v)throw error||new Error('Veículo não encontrado');vehicle=v;settings=s||{};render()}catch(error){document.querySelector('#vehicle-content').innerHTML=`<div class="vehicle-error"><p class="eyebrow dark">Estoque</p><h1>Veículo não encontrado.</h1><p>Ele pode ter sido removido ou ainda não está publicado.</p><a class="btn btn-dark" href="index.html#estoque">Voltar ao estoque</a></div>`}}
document.querySelector('#sticky-favorite').onclick=()=>{const key='ldp-favorites',list=JSON.parse(localStorage.getItem(key)||'[]'),id=String(vehicle.id),next=list.includes(id)?list.filter(x=>x!==id):[...list,id];localStorage.setItem(key,JSON.stringify(next));document.querySelector('#sticky-favorite').textContent=next.includes(id)?'Salvo':'Salvar'};
init();

