document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/admin/admin-mobile.css">');
const client=window.supabaseClient;let allVehicles=[],currentUser=null,currentRole=null,accessPoll=null;const OWNER_EMAIL='andrenevessato04@gmail.com';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const money=n=>window.LDP_CURRENCY.format(n,'Não informado');
function status(msg,error=false,root=document){const el=root.querySelector('.status');if(el){el.textContent=msg;el.style.color=error?'#e66':'#24bd69'}}
async function init(){if(!client){status('Supabase ainda não foi configurado.',true);return}const{data:{session}}=await client.auth.getSession();session?authorize(session.user):showAuth();client.auth.onAuthStateChange((event,s)=>{if(event==='INITIAL_SESSION')return;setTimeout(()=>s?authorize(s.user):showAuth(),0)})}
function stopAccessPoll(){if(accessPoll){clearInterval(accessPoll);accessPoll=null}}
function showAuth(){stopAccessPoll();$('#auth-view').classList.remove('hidden');$('#app-view').classList.add('hidden');$('#access-lock').classList.add('hidden')}
function showBlocked(user,state='pending'){currentUser=user;$('#auth-view').classList.add('hidden');$('#app-view').classList.add('hidden');$('#access-lock').classList.remove('hidden');$('#access-lock-email').textContent=user.email||'';const rejected=state==='rejected';$('#access-lock-title').textContent=rejected?'Acesso não autorizado':'Solicitação em análise';$('#access-lock-message').textContent=rejected?'Você não possui autorização para acessar este painel. Uma nova solicitação só será criada se você escolher solicitar novamente.':'Seu pedido de acesso ainda está aguardando aprovação.';$('.access-lock-pulse').classList.toggle('hidden',rejected);$('#request-access-again').classList.toggle('hidden',!rejected);stopAccessPoll();if(!rejected)accessPoll=setInterval(()=>authorize(user,{silent:true}),5000)}
async function authorize(user,{silent=false}={}){const{data:profile,error}=await client.from('admin_profiles').select('role,active').eq('user_id',user.id).maybeSingle();if(!error&&profile?.active){currentRole=profile.role;stopAccessPoll();await showApp(user);return}const{data}=await client.from('admin_access_requests').select('status,requested_at').eq('user_id',user.id).order('requested_at',{ascending:false}).limit(1).maybeSingle();showBlocked(user,data?.status||'pending');if(error&&!silent)$('#access-lock-message').textContent='Não foi possível validar sua autorização agora.'}
async function showApp(user){stopAccessPoll();currentUser=user;$('#auth-view').classList.add('hidden');$('#access-lock').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-email').textContent=user.email;$('#sidebar-user').textContent=user.email;const isOwner=currentRole==='owner';$('#access-tab').classList.toggle('hidden',!isOwner);await Promise.all([loadVehicles(),loadSettings(),loadLeads(),isOwner?loadAccessRequests():Promise.resolve()])}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();status('Entrando…');const d=new FormData(e.target);const{error}=await client.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});status(error?error.message:'Login realizado.',!!error)});
const passwordInput=$('#password-input'),togglePassword=$('#toggle-password');
passwordInput.addEventListener('input',()=>{togglePassword.hidden=!passwordInput.value;if(!passwordInput.value){passwordInput.type='password';togglePassword.setAttribute('aria-label','Mostrar senha');togglePassword.title='Mostrar senha'}});
togglePassword.addEventListener('click',()=>{const willShow=passwordInput.type==='password';passwordInput.type=willShow?'text':'password';const label=willShow?'Ocultar senha':'Mostrar senha';togglePassword.setAttribute('aria-label',label);togglePassword.title=label;passwordInput.focus()});
$('#signup').onclick=()=>{window.location.href='/admin/cadastro.html'};const recoveryButton=document.createElement('button');recoveryButton.type='button';recoveryButton.className='secondary';recoveryButton.textContent='Esqueci minha senha';recoveryButton.onclick=()=>{window.location.href='/admin/recuperar.html'};$('#signup').insertAdjacentElement('afterend',recoveryButton);$('#logout').onclick=()=>client.auth.signOut();$('#access-lock-logout').onclick=()=>client.auth.signOut();
$('#request-access-again').onclick=async()=>{if(!currentUser)return;const button=$('#request-access-again');button.disabled=true;button.textContent='Enviando solicitação…';const{error}=await client.from('admin_access_requests').insert({user_id:currentUser.id,email:currentUser.email,status:'pending',requested_at:new Date().toISOString()});button.disabled=false;if(error){button.textContent='Não foi possível solicitar novamente';return}button.textContent='Solicitação enviada';showBlocked(currentUser,'pending')};
const adminAside=$('#app-view aside');adminAside.insertAdjacentHTML('afterend','<button class="admin-overlay" id="admin-overlay" type="button" aria-label="Fechar menu"></button>');$('#app-view main>header').insertAdjacentHTML('afterbegin','<button class="admin-menu-toggle" id="admin-menu-toggle" type="button" aria-label="Abrir menu" aria-expanded="false">☰</button>');
function closeAdminMenu(){adminAside.classList.remove('open');document.body.classList.remove('admin-menu-open');$('#admin-menu-toggle').setAttribute('aria-expanded','false')}
$('#admin-menu-toggle').onclick=()=>{const open=!adminAside.classList.contains('open');adminAside.classList.toggle('open',open);document.body.classList.toggle('admin-menu-open',open);$('#admin-menu-toggle').setAttribute('aria-expanded',String(open))};$('#admin-overlay').onclick=closeAdminMenu;
function changeTab(tab){$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==tab));$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const labels={dashboard:'Visão Geral',vehicles:'Veículos',leads:'Leads',pipeline:'Pipeline',marketing:'Marketing',intelligence:'Análises IA',access:'Novos Acessos',settings:'Configurações'};$('#page-title').textContent=labels[tab];$('#breadcrumb-current').textContent=labels[tab];closeAdminMenu();if(tab==='access')loadAccessRequests();if(tab==='leads')loadLeads();if(tab==='pipeline')renderPipeline(window.__adminLeads||[])}
$$('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>changeTab(b.dataset.go));
async function loadVehicles(){const{data,error}=await client.from('vehicles').select('*').order('created_at',{ascending:false});if(error){status(error.message,true);return}allVehicles=data||[];renderVehicles(allVehicles);$('#stat-total').textContent=`${allVehicles.length} cadastrados`;$('#stat-active').textContent=allVehicles.filter(v=>v.active).length;$('#stat-featured').textContent=allVehicles.filter(v=>v.featured).length;renderAttention()}
function safeImageUrl(value){try{const url=new URL(value,location.origin);return ['https:','http:'].includes(url.protocol)?url.href:'/assets/hero-showroom.png'}catch{return'/assets/hero-showroom.png'}}
function renderVehicles(list){$('#vehicle-count').textContent=`${list.length} veículo${list.length===1?'':'s'}`;$('#admin-empty').classList.toggle('hidden',list.length>0);$('#vehicle-list').innerHTML=list.map(v=>`<tr><td><div class="vehicle-name"><img src="${escapeHtml(safeImageUrl(v.image_url))}" alt=""><div><b>${escapeHtml(v.brand)} ${escapeHtml(v.model)}</b><small>${(v.vehicle_type||'car')==='motorcycle'?'Moto':'Carro'} • ${escapeHtml(v.version||'Versão a definir')}${v.newly_arrived?' • Novo no estoque':''}</small></div></div></td><td>${escapeHtml(v.year)}</td><td>${escapeHtml(money(v.price))}</td><td><span class="badge ${v.active?'':'off'}">${escapeHtml(v.active?({available:'Disponível',reserved:'Reservado',sold:'Vendido',preparing:'Em preparação'}[v.status||'available']):'Oculto')}</span></td><td><div class="actions"><a class="view" href="/vehicle?slug=${encodeURIComponent(v.slug||'')}" target="_blank" rel="noopener">Ver no site</a><button data-edit="${escapeHtml(v.id)}">Editar</button><button class="delete" data-delete="${escapeHtml(v.id)}">Mover para lixeira</button></div></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openVehicle(allVehicles.find(v=>String(v.id)===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>removeVehicle(b.dataset.delete))}
$('#search').oninput=e=>{const q=e.target.value.toLowerCase();renderVehicles(allVehicles.filter(v=>`${v.brand} ${v.model} ${v.version}`.toLowerCase().includes(q)))};
const dialog=$('#vehicle-dialog'),form=$('#vehicle-form');form.querySelector('[name="category"]').closest('label').insertAdjacentHTML('beforebegin','<label>Tipo de veículo<select name="vehicle_type"><option value="car">Carro</option><option value="motorcycle">Moto</option></select></label>');form.querySelector('[name="category"]').closest('label').insertAdjacentHTML('afterend','<label>Carroceria<input name="body_type" placeholder="SUV, cupê, picape..."></label><label>Categoria de destaque<select name="highlight_category"><option value="">Sem categoria</option><option>Premium</option><option>Luxo</option><option>Esportivo</option><option>Escolha da Loja</option><option>Novidade</option><option>Oportunidade</option></select></label><label>Ordem nos destaques<input name="highlight_position" type="number" min="1"></label><label>Posição na Home<input name="home_position" type="number" min="1"></label>');form.elements.status.insertAdjacentHTML('beforeend','<option value="preparing">Em preparação</option>');$('#new-vehicle').onclick=()=>openVehicle();function openVehicle(v){form.reset();form.active.checked=true;form.keep_sold_public.checked=true;$('#dialog-title').textContent=v?'Editar veículo':'Novo veículo';if(v){for(const[k,val]of Object.entries(v)){if(!form.elements[k])continue;if(form.elements[k].type==='checkbox')form.elements[k].checked=!!val;else form.elements[k].value=['features','image_urls','tags','lifestyle_categories'].includes(k)?(val||[]).join('\n'):(val??'')}}dialog.showModal()}
form.addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return;const d=Object.fromEntries(new FormData(form)),lines=name=>d[name]?d[name].split('\n').map(x=>x.trim()).filter(Boolean):[];const slug=`${d.brand}-${d.model}-${d.version||''}-${d.year}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const payload={vehicle_type:d.vehicle_type||'car',brand:d.brand,model:d.model,version:d.version||null,year:+d.year,mileage:d.mileage?+d.mileage:0,price:d.price?+d.price:null,installment:d.installment?+d.installment:null,status:d.status||'available',transmission:d.transmission||null,fuel:d.fuel||null,color:d.color||null,category:d.category||null,body_type:d.body_type||null,highlight_category:d.highlight_category||null,highlight_position:d.highlight_position?+d.highlight_position:null,home_position:d.home_position?+d.home_position:null,image_url:d.image_url||null,image_urls:lines('image_urls'),description:d.description||null,features:lines('features'),tags:lines('tags'),lifestyle_categories:lines('lifestyle_categories'),slug,featured:form.featured.checked,newly_arrived:form.newly_arrived.checked,keep_sold_public:form.keep_sold_public.checked,active:form.active.checked};status('Salvando…',false,form);const query=d.id?client.from('vehicles').update(payload).eq('id',d.id):client.from('vehicles').insert(payload);const{error}=await query;if(error){status(error.message,true,form);return}dialog.close();await loadVehicles()});
async function removeVehicle(id){if(!confirm('Mover este veículo para a lixeira? Ele poderá ser restaurado pelo banco.'))return;const{error}=await client.from('vehicles').update({active:false,deleted_at:new Date().toISOString(),deleted_by:currentUser.id}).eq('id',id);if(error)alert('Não foi possível mover o veículo para a lixeira.');else loadVehicles()}
$('#settings-form button[type="submit"]').insertAdjacentHTML('beforebegin','<label class="wide"><strong>Nossa história — título</strong><input name="history_title" placeholder="Nossa história"></label><label class="wide">Subtítulo institucional<input name="history_subtitle"></label><label class="wide">Texto da história<textarea name="history_text" rows="7" placeholder="Escreva somente informações reais sobre a trajetória da loja."></textarea></label><label>Logo institucional (URL)<input name="history_logo_url" type="url"></label><label>Imagem institucional (URL)<input name="history_image_url" type="url"></label><label class="wide">Galeria institucional<textarea name="history_gallery" rows="4" placeholder="Uma URL por linha"></textarea></label><label class="wide">Linha do tempo<textarea name="history_timeline" rows="5" placeholder="Ano | Título | Texto — uma etapa por linha"></textarea></label><label class="wide">Valores da loja<textarea name="store_values" rows="5" placeholder="Título | Texto — um valor por linha"></textarea></label><label class="wide">Equipe<textarea name="team_members" rows="5" placeholder="Nome | Função | Foto URL | WhatsApp"></textarea></label><label class="wide">Perguntas frequentes<textarea name="faqs" rows="6" placeholder="Pergunta | Resposta — uma por linha"></textarea></label><label class="wide">Categorias de descoberta<textarea name="lifestyle_categories" rows="4" placeholder="Primeiro carro — uma por linha"></textarea></label>');
async function loadSettings(){const{data}=await client.from('store_settings').select('*').eq('id',1).maybeSingle();if(data)for(const[k,v]of Object.entries(data))if($('#settings-form').elements[k])$('#settings-form').elements[k].value=k==='faqs'?(v||[]).map(x=>`${x.question||''} | ${x.answer||''}`).join('\n'):['lifestyle_categories','history_gallery'].includes(k)?(v||[]).join('\n'):k==='history_timeline'?(v||[]).map(x=>`${x.year||''} | ${x.title||''} | ${x.text||''}`).join('\n'):k==='store_values'?(v||[]).map(x=>`${x.title||''} | ${x.text||''}`).join('\n'):k==='team_members'?(v||[]).map(x=>`${x.name||''} | ${x.role||''} | ${x.image||''} | ${x.whatsapp||''}`).join('\n'):(v||'')}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));payload.id=1;const rows=name=>(payload[name]||'').split('\n').map(x=>x.trim()).filter(Boolean);payload.faqs=rows('faqs').map(line=>{const[question,...answer]=line.split('|');return{question:question?.trim(),answer:answer.join('|').trim()}}).filter(x=>x.question&&x.answer);payload.lifestyle_categories=rows('lifestyle_categories');payload.history_gallery=rows('history_gallery');payload.history_timeline=rows('history_timeline').map(line=>{const[year,title,...text]=line.split('|');return{year:year?.trim(),title:title?.trim(),text:text.join('|').trim()}});payload.store_values=rows('store_values').map(line=>{const[title,...text]=line.split('|');return{title:title?.trim(),text:text.join('|').trim()}});payload.team_members=rows('team_members').map(line=>{const[name,role,image,whatsapp]=line.split('|');return{name:name?.trim(),role:role?.trim(),image:image?.trim(),whatsapp:whatsapp?.trim()}});status('Salvando…',false,e.target);const{error}=await client.from('store_settings').upsert(payload);status(error?error.message:'Configurações publicadas com sucesso.',!!error,e.target)});
async function loadAccessRequests(){if(!currentUser||currentUser.email.toLowerCase()!==OWNER_EMAIL)return;const{data,error}=await client.from('admin_access_requests').select('*').neq('email',OWNER_EMAIL).order('requested_at',{ascending:false});if(error){status(error.message,true,$('[data-panel="access"]'));return}const requests=data||[],pending=requests.filter(r=>r.status==='pending'),history=requests.filter(r=>r.status!=='pending');$('#access-count').textContent=pending.length;$('#access-count').classList.toggle('hidden',pending.length===0);$('#access-pending-kpi').textContent=pending.length;$('#access-approved-kpi').textContent=requests.filter(r=>r.status==='approved').length;$('#access-rejected-kpi').textContent=requests.filter(r=>r.status==='rejected').length;$('#access-empty').classList.toggle('hidden',pending.length>0);$('#access-history-empty').classList.toggle('hidden',history.length>0);$('#access-list').innerHTML=pending.map(r=>`<tr><td><b>${escapeHtml(r.name||'Usuário')}</b><small>${escapeHtml(r.email)}</small></td><td>${new Date(r.requested_at).toLocaleString('pt-BR')}</td><td><span class="badge access-pending">Pendente</span></td><td><div class="actions"><button class="approve" data-access="approved" data-user="${r.user_id}">Aprovar acesso</button><button class="delete" data-access="rejected" data-user="${r.user_id}">Recusar acesso</button></div></td></tr>`).join('');$('#access-history-list').innerHTML=history.map(r=>`<tr><td><b>${escapeHtml(r.name||'Usuário')}</b><small>${escapeHtml(r.email)}</small></td><td>${new Date(r.requested_at).toLocaleString('pt-BR')}</td><td><span class="badge access-${r.status}">${r.status==='approved'?'Aprovado':'Recusado'}</span></td><td>${r.reviewed_at?new Date(r.reviewed_at).toLocaleString('pt-BR'):'—'}</td></tr>`).join('');$$('[data-access]').forEach(b=>b.onclick=()=>reviewAccess(b.dataset.user,b.dataset.access))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function reviewAccess(userId,nextStatus){const action=nextStatus==='approved'?'aprovar':'recusar';if(!confirm(`Deseja ${action} este acesso?`))return;status('Atualizando acesso…',false,$('[data-panel="access"]'));const{error}=await client.rpc('review_admin_access',{target_user:userId,decision:nextStatus,requested_role:'sales'});status(error?'Não foi possível atualizar o acesso.':nextStatus==='approved'?'Acesso aprovado como Vendedor.':'Acesso recusado.',!!error,$('[data-panel="access"]'));if(!error)loadAccessRequests()}
async function loadLeads(){const{data,error}=await client.from('leads').select('*').order('created_at',{ascending:false}).limit(200);if(error){status(error.message,true,$('[data-panel="leads"]'));return}const leads=data||[];window.__adminLeads=leads;const fresh=leads.filter(x=>x.status==='new').length;$('#lead-count').textContent=fresh;$('#lead-count').classList.toggle('hidden',fresh===0);$('#stat-leads').textContent=leads.length;$('#stat-new-leads').textContent=fresh;$('#stat-leads-note').textContent=leads.length?'Registros no banco':'Nenhum registro';$('#lead-empty').classList.toggle('hidden',leads.length>0);const origins={home_financing:'Financiamento',home_trade:'Avaliação',journey_financing:'Financiamento',journey_trade:'Troca',journey_sell:'Venda',sell_page:'Venda'};const rows=leads.map(x=>`<tr><td><b>${escapeHtml(x.name||'Sem nome')}</b><small>${escapeHtml(x.phone||x.email||'Contato não informado')}</small></td><td>${escapeHtml(x.vehicle_interest||'A consultar')}</td><td>${origins[x.source]||escapeHtml(x.source||'Site')}</td><td>${new Date(x.created_at).toLocaleString('pt-BR')}</td><td><select data-lead-status="${x.id}"><option value="new" ${x.status==='new'?'selected':''}>Novo</option><option value="contacted" ${x.status==='contacted'?'selected':''}>Em contato</option><option value="closed" ${x.status==='closed'?'selected':''}>Concluído</option></select></td></tr>`).join('');$('#lead-list').innerHTML=rows;const recent=leads.slice(0,6);$('#recent-leads-empty').classList.toggle('hidden',recent.length>0);$('#recent-leads').innerHTML=recent.map(x=>`<tr><td><b>${escapeHtml(x.name||'Sem nome')}</b></td><td>${escapeHtml(x.vehicle_interest||'A consultar')}</td><td>${origins[x.source]||'Site'}</td><td><span class="badge">${x.status==='new'?'Novo':x.status==='contacted'?'Em contato':'Concluído'}</span></td><td>${new Date(x.created_at).toLocaleDateString('pt-BR')}</td></tr>`).join('');renderPipeline(leads);renderAttention();$('#ai-operation-summary').textContent=leads.length?`A operação possui ${leads.length} lead${leads.length===1?'':'s'} registrado${leads.length===1?'':'s'}, com ${fresh} aguardando atendimento. Dados de mídia ainda não estão integrados.`:'Dados insuficientes para análise.';$$('[data-lead-status]').forEach(select=>select.onchange=async()=>{const{error}=await client.from('leads').update({status:select.value,updated_at:new Date().toISOString()}).eq('id',select.dataset.leadStatus);if(error)status(error.message,true,$('[data-panel="leads"]'));else loadLeads()})}

function renderPipeline(leads){const stages=[['new','Novo'],['contacted','Contato iniciado'],['closed','Concluído']];$('#pipeline-board').innerHTML=stages.map(([key,label])=>`<section><header><strong>${label}</strong><span>${leads.filter(x=>x.status===key).length}</span></header>${leads.filter(x=>x.status===key).map(x=>`<article><b>${escapeHtml(x.name||'Sem nome')}</b><small>${escapeHtml(x.vehicle_interest||'Interesse a consultar')}</small><em>${new Date(x.created_at).toLocaleDateString('pt-BR')}</em></article>`).join('')||'<p>Nenhum lead nesta etapa.</p>'}</section>`).join('')}
function renderAttention(){const leads=window.__adminLeads||[],fresh=leads.filter(x=>x.status==='new').length,items=[];if(fresh)items.push(`<button data-go="leads"><strong>${fresh} lead${fresh===1?'':'s'} sem atendimento</strong><span>Abrir central de leads</span></button>`);const inactive=allVehicles.filter(v=>!v.active).length;if(inactive)items.push(`<button data-go="vehicles"><strong>${inactive} veículo${inactive===1?'':'s'} oculto${inactive===1?'':'s'}</strong><span>Revisar estoque</span></button>`);if(!items.length)items.push('<div class="attention-ok"><strong>Nenhuma pendência crítica</strong><span>A operação não possui alertas calculáveis agora.</span></div>');$('#attention-list').innerHTML=items.join('');$$('#attention-list [data-go]').forEach(b=>b.onclick=()=>changeTab(b.dataset.go))}
$('#refresh-leads').onclick=loadLeads;
$('#refresh-access').onclick=loadAccessRequests;
if(new URLSearchParams(location.search).get('confirmed'))status('E-mail confirmado. Entre para consultar a aprovação do seu acesso.');
const whatsappField=$('#settings-form [name="whatsapp"]');whatsappField.type='url';whatsappField.closest('label').childNodes[0].textContent='Link principal do WhatsApp ';whatsappField.placeholder=window.LDP_WHATSAPP.official;whatsappField.insertAdjacentHTML('afterend','<small class="field-hint">Use um link oficial https://wa.me/. Todos os botões do site utilizam esta configuração.</small>');
$('#settings-form').addEventListener('submit',e=>{const link=whatsappField.value.trim();if(!/^https:\/\/wa\.me\/(?:message\/)?[A-Za-z0-9]+\/?(?:\?.*)?$/i.test(link)){e.preventDefault();e.stopImmediatePropagation();status('Informe um link oficial válido do WhatsApp iniciado por https://wa.me/.',true,e.currentTarget);whatsappField.focus();return}whatsappField.value=link;const button=e.currentTarget.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Publicando…';setTimeout(()=>{button.disabled=false;button.textContent='Salvar configurações'},2500)},true);
$('#admin-global-search').addEventListener('keydown',e=>{if(e.key!=='Enter')return;e.preventDefault();const q=e.currentTarget.value.trim().toLowerCase();if(!q)return;const matches=allVehicles.filter(v=>`${v.brand} ${v.model} ${v.version||''}`.toLowerCase().includes(q));changeTab('vehicles');$('#search').value=q;renderVehicles(matches)});
$('.notification-button').onclick=()=>changeTab(currentUser?.email?.toLowerCase()===OWNER_EMAIL?'access':'leads');
const settingsSubmitButton=$('#settings-form button[type="submit"]');
settingsSubmitButton.insertAdjacentHTML('beforebegin','<label class="wide"><strong>Link do grupo</strong><input name="group_offers_link" type="url" placeholder="https://chat.whatsapp.com/..."><small class="field-hint">Quando vazio, o card continua visível com a indicação “Link em configuração”.</small></label>');
let groupOffersEntries=[];
async function loadGroupOffersAdmin(){const{data}=await client.from('store_settings').select('testimonials').eq('id',1).maybeSingle();groupOffersEntries=Array.isArray(data?.testimonials)?data.testimonials:[];const item=groupOffersEntries.find(x=>x?.type==='group_offers');$('#settings-form').elements.group_offers_link.value=item?.url||'https://chat.whatsapp.com/CFj0yqNe9AZLV4oy124zOY?mode=gi_t'}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const payload=Object.fromEntries(new FormData(e.target));payload.id=1;const groupLink=String(payload.group_offers_link||'').trim();delete payload.group_offers_link;payload.testimonials=groupOffersEntries.filter(x=>x?.type!=='group_offers');if(groupLink)payload.testimonials.push({type:'group_offers',url:groupLink});const rows=name=>(payload[name]||'').split('\n').map(x=>x.trim()).filter(Boolean);payload.faqs=rows('faqs').map(line=>{const[question,...answer]=line.split('|');return{question:question?.trim(),answer:answer.join('|').trim()}}).filter(x=>x.question&&x.answer);payload.lifestyle_categories=rows('lifestyle_categories');payload.history_gallery=rows('history_gallery');payload.history_timeline=rows('history_timeline').map(line=>{const[year,title,...text]=line.split('|');return{year:year?.trim(),title:title?.trim(),text:text.join('|').trim()}});payload.store_values=rows('store_values').map(line=>{const[title,...text]=line.split('|');return{title:title?.trim(),text:text.join('|').trim()}});payload.team_members=rows('team_members').map(line=>{const[name,role,image,whatsapp]=line.split('|');return{name:name?.trim(),role:role?.trim(),image:image?.trim(),whatsapp:whatsapp?.trim()}});status('Salvando…',false,e.target);const{error}=await client.from('store_settings').upsert(payload);if(!error){groupOffersEntries=payload.testimonials}status(error?error.message:'Configurações publicadas com sucesso.',!!error,e.target)},true);
init();
loadGroupOffersAdmin();

