const client=window.supabaseClient;let allVehicles=[];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const money=n=>n?Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}):'[A DEFINIR]';
function status(msg,error=false,root=document){const el=root.querySelector('.status');if(el){el.textContent=msg;el.style.color=error?'#e66':'#24bd69'}}
async function init(){if(!client){status('Supabase ainda não foi configurado.',true);return}const{data:{session}}=await client.auth.getSession();session?showApp(session.user):showAuth();client.auth.onAuthStateChange((_e,s)=>setTimeout(()=>s?showApp(s.user):showAuth(),0))}
function showAuth(){$('#auth-view').classList.remove('hidden');$('#app-view').classList.add('hidden')}
async function showApp(user){$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-email').textContent=user.email;await Promise.all([loadVehicles(),loadSettings()])}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();status('Entrando…');const d=new FormData(e.target);const{error}=await client.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});status(error?error.message:'Login realizado.',!!error)});
$('#signup').onclick=async()=>{const f=$('#login-form'),d=new FormData(f);if(!d.get('email')||!d.get('password')){status('Preencha e-mail e senha antes de criar o acesso.',true);return}const{error}=await client.auth.signUp({email:d.get('email'),password:d.get('password')});status(error?error.message:'Conta criada. Confira seu e-mail para confirmar o acesso.',!!error)};$('#logout').onclick=()=>client.auth.signOut();
function changeTab(tab){$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==tab));$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#page-title').textContent={dashboard:'Visão geral',vehicles:'Veículos',settings:'Configurações'}[tab]}
$$('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>changeTab(b.dataset.go));
async function loadVehicles(){const{data,error}=await client.from('vehicles').select('*').order('created_at',{ascending:false});if(error){alert(error.message);return}allVehicles=data||[];renderVehicles(allVehicles);$('#stat-total').textContent=allVehicles.length;$('#stat-active').textContent=allVehicles.filter(v=>v.active).length;$('#stat-featured').textContent=allVehicles.filter(v=>v.featured).length}
function renderVehicles(list){$('#vehicle-count').textContent=`${list.length} veículo${list.length===1?'':'s'}`;$('#admin-empty').classList.toggle('hidden',list.length>0);$('#vehicle-list').innerHTML=list.map(v=>`<tr><td><div class="vehicle-name"><img src="${v.image_url||'../assets/hero-showroom.png'}" alt=""><div><b>${v.brand} ${v.model}</b><small>${v.version||'Versão a definir'}</small></div></div></td><td>${v.year}</td><td>${money(v.price)}</td><td><span class="badge ${v.active?'':'off'}">${v.active?'Publicado':'Oculto'}</span></td><td><div class="actions"><button data-edit="${v.id}">Editar</button><button class="delete" data-delete="${v.id}">Excluir</button></div></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openVehicle(allVehicles.find(v=>v.id===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>removeVehicle(b.dataset.delete))}
$('#search').oninput=e=>{const q=e.target.value.toLowerCase();renderVehicles(allVehicles.filter(v=>`${v.brand} ${v.model} ${v.version}`.toLowerCase().includes(q)))};
const dialog=$('#vehicle-dialog'),form=$('#vehicle-form');$('#new-vehicle').onclick=()=>openVehicle();function openVehicle(v){form.reset();form.active.checked=true;$('#dialog-title').textContent=v?'Editar veículo':'Novo veículo';if(v){for(const[k,val]of Object.entries(v)){if(!form.elements[k])continue;if(form.elements[k].type==='checkbox')form.elements[k].checked=!!val;else form.elements[k].value=k==='features'?(val||[]).join('\n'):(val??'')}}dialog.showModal()}
form.addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return;const d=Object.fromEntries(new FormData(form));const payload={brand:d.brand,model:d.model,version:d.version||null,year:+d.year,mileage:d.mileage?+d.mileage:0,price:d.price?+d.price:null,installment:d.installment?+d.installment:null,transmission:d.transmission||null,fuel:d.fuel||null,color:d.color||null,category:d.category||null,image_url:d.image_url||null,features:d.features?d.features.split('\n').map(x=>x.trim()).filter(Boolean):[],featured:form.featured.checked,active:form.active.checked};status('Salvando…',false,form);const query=d.id?client.from('vehicles').update(payload).eq('id',d.id):client.from('vehicles').insert(payload);const{error}=await query;if(error){status(error.message,true,form);return}dialog.close();await loadVehicles()});
async function removeVehicle(id){if(!confirm('Excluir este veículo permanentemente?'))return;const{error}=await client.from('vehicles').delete().eq('id',id);if(error)alert(error.message);else loadVehicles()}
async function loadSettings(){const{data}=await client.from('store_settings').select('*').eq('id',1).maybeSingle();if(data)for(const[k,v]of Object.entries(data))if($('#settings-form').elements[k])$('#settings-form').elements[k].value=v||''}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));payload.id=1;status('Salvando…',false,e.target);const{error}=await client.from('store_settings').upsert(payload);status(error?error.message:'Configurações publicadas com sucesso.',!!error,e.target)});
init();

