(()=>{
  const opts=window.VEHICLE_OPTIONS,form=document.querySelector('#vehicle-form'),dialog=document.querySelector('#vehicle-dialog');
  if(!opts||!form)return;
  document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/admin/admin-vehicle.css">');
  const optionList=(items,selected='')=>items.map(item=>`<option value="${item}" ${item===selected?'selected':''}>${item||'Sem categoria'}</option>`).join('');
  const chipList=(name,items,selected=[])=>items.map(item=>`<label class="chip-option"><input type="checkbox" name="${name}" value="${item}" ${selected.includes(item)?'checked':''}><span>${item}</span></label>`).join('');
  let gallery=[],removedStorage=[];
  const formMarkup=`<header><div><p class="overline">Estoque / Cadastro</p><h2 id="dialog-title">Novo veículo</h2></div><button type="button" id="close-vehicle" aria-label="Fechar">×</button></header><input type="hidden" name="id"><div class="vehicle-form-body">
    <section class="vehicle-section"><h3>1. Tipo do veículo</h3><p>O restante do formulário será adaptado automaticamente.</p><div class="vehicle-type-switch">${opts.types.map(([value,label])=>`<label><input type="radio" name="vehicle_type" value="${value}" ${value==='car'?'checked':''}><span>${label}</span></label>`).join('')}</div></section>
    <section class="vehicle-section"><h3>2. Informações básicas</h3><div class="vehicle-section-grid"><label>Marca *<input required name="brand" autocomplete="off"></label><label>Modelo *<input required name="model" autocomplete="off"></label><label>Versão<input name="version"></label><label>Ano *<input required name="year" type="number" inputmode="numeric" min="1950" max="2100"></label><label>Cor<select name="color">${optionList(opts.colors)}</select></label></div></section>
    <section class="vehicle-section"><h3>3. Características</h3><div class="vehicle-section-grid"><label id="body-type-label">Tipo / Carroceria *<select required name="body_type"></select></label><label>Câmbio<select name="transmission"></select></label><label>Combustível<select name="fuel"></select></label><label>Quilometragem<input name="mileage" inputmode="numeric" pattern="[0-9.]*" placeholder="Ex.: 63000"><small class="money-preview" data-preview="mileage"></small></label></div></section>
    <section class="vehicle-section"><h3>4. Preço</h3><p>Digite somente o valor em reais. Ex.: 100000 será exibido como R$ 100.000,00.</p><div class="vehicle-section-grid"><label>Preço *<span class="currency-control"><b>R$</b><input required name="price_display" data-currency="price" inputmode="numeric" autocomplete="off" placeholder="100.000,00"></span><input type="hidden" name="price"></label><label>Parcela estimada<span class="currency-control"><b>R$</b><input name="installment_display" data-currency="installment" inputmode="numeric" autocomplete="off" placeholder="1.899,00"></span><input type="hidden" name="installment"><small class="money-preview" data-preview="installment"></small></label></div></section>
    <section class="vehicle-section"><h3>5. Fotos</h3><p>A primeira foto será a imagem principal. JPEG, PNG, WebP ou AVIF, até 10 MB.</p><label class="upload-zone" id="vehicle-upload-zone"><input id="vehicle-images-input" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple><span><strong>+ Adicionar fotos</strong><small>Toque para abrir a galeria ou arraste arquivos aqui</small></span></label><div class="gallery-grid" id="vehicle-gallery"></div><p class="existing-image-note" id="gallery-empty">Nenhuma foto selecionada.</p></section>
    <section class="vehicle-section"><h3>6. Equipamentos</h3><p>Marque somente o que este veículo possui.</p><div class="chip-grid" id="feature-options"></div><div class="custom-row"><label>Outro equipamento<input id="custom-feature" placeholder="Adicionar item específico"></label><button type="button" id="add-feature">Adicionar</button></div></section>
    <section class="vehicle-section"><h3>7. Descrição</h3><label>Descrição real do veículo<textarea name="description" rows="5" placeholder="Conservação, histórico e diferenciais reais."></textarea></label><label>Tags adicionais<div class="chip-grid" id="tag-options">${chipList('tag_choice',opts.tags)}</div></label></section>
    <section class="vehicle-section"><h3>8. Publicação</h3><div class="vehicle-section-grid"><label>Status<select name="status"><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="preparing">Em preparação</option><option value="sold">Vendido</option></select></label><label>Categoria comercial<select name="category">${optionList(opts.commercialCategories)}</select></label><label>Categoria de destaque<select name="highlight_category">${optionList(opts.highlights)}</select></label><label>Ordem nos destaques<input name="highlight_position" type="number" inputmode="numeric" min="1"></label><label>Posição na Home<input name="home_position" type="number" inputmode="numeric" min="1"></label></div><div class="chip-grid"><label class="chip-option"><input name="featured" type="checkbox"><span>Destaque</span></label><label class="chip-option"><input name="newly_arrived" type="checkbox"><span>Acabou de chegar</span></label><label class="chip-option"><input name="keep_sold_public" type="checkbox" checked><span>Manter vendido público</span></label><label class="chip-option"><input name="active" type="checkbox" checked><span>Visível no site</span></label></div></section>
  </div><footer><p class="status form-status" role="status" aria-live="polite"></p><button class="secondary" type="button" id="cancel-vehicle">Cancelar</button><button id="save-vehicle" value="default">Salvar veículo</button></footer>`;
  form.innerHTML=formMarkup;
  const el=s=>form.querySelector(s),all=s=>[...form.querySelectorAll(s)],digits=v=>String(v||'').replace(/\D/g,''),escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function setStatus(message,isError=false){const node=el('.status');node.textContent=message;node.style.color=isError?'#b42318':'#188f50'}
  function type(){return el('[name="vehicle_type"]:checked')?.value||'car'}
  function syncType(clear=false){const current=type(),body=el('[name="body_type"]'),old=clear?'':body.value;el('#body-type-label').childNodes[0].textContent=current==='car'?'Tipo / Carroceria *':'Tipo da moto *';body.innerHTML='<option value="">Selecione</option>'+optionList(opts.bodyTypes[current]);body.value=opts.bodyTypes[current].includes(old)?old:'';el('[name="transmission"]').innerHTML=optionList(opts.transmissions[current]);el('[name="fuel"]').innerHTML=optionList(opts.fuels[current]);renderFeatures([])}
  function selectedFeatures(){return all('[name="feature_choice"]:checked').map(x=>x.value)}
  function renderFeatures(selected=[]){const choices=[...new Set([...opts.features[type()],...selected])];el('#feature-options').innerHTML=chipList('feature_choice',choices,selected)}
  function objectUrl(item){return item.file?URL.createObjectURL(item.file):item.url}
  function renderGallery(){const root=el('#vehicle-gallery');root.innerHTML=gallery.map((item,index)=>`<article class="gallery-item ${index===0?'main':''}" data-gallery-index="${index}" draggable="true"><img src="${escape(objectUrl(item))}" alt="Foto ${index+1}">${index===0?'<span class="main-badge">Principal</span>':''}<div class="gallery-item-actions"><button type="button" data-move="left" aria-label="Mover para esquerda">←</button><button type="button" data-main aria-label="Definir como principal">★</button><button type="button" data-move="right" aria-label="Mover para direita">→</button><button type="button" data-remove aria-label="Remover foto">×</button></div></article>`).join('');el('#gallery-empty').hidden=gallery.length>0}
  const allowedTypes=new Set(['image/jpeg','image/png','image/webp','image/avif']);
  function addFiles(files){for(const file of files){if(!allowedTypes.has(file.type)){setStatus(`${file.name} não possui um formato permitido.`,true);continue}if(file.size>10*1024*1024){setStatus(`${file.name} excede 10 MB.`,true);continue}gallery.push({file})}renderGallery()}
  const input=el('#vehicle-images-input'),zone=el('#vehicle-upload-zone');input.onchange=()=>{addFiles(input.files);input.value=''};['dragenter','dragover'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.remove('drag')}));zone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
  el('#vehicle-gallery').addEventListener('click',e=>{const item=e.target.closest('[data-gallery-index]');if(!item)return;const index=+item.dataset.galleryIndex;if(e.target.closest('[data-remove]')){const[removed]=gallery.splice(index,1);if(removed?.storagePath)removedStorage.push(removed.storagePath)}else if(e.target.closest('[data-main]'))gallery.unshift(...gallery.splice(index,1));else if(e.target.closest('[data-move="left"]')&&index>0)[gallery[index-1],gallery[index]]=[gallery[index],gallery[index-1]];else if(e.target.closest('[data-move="right"]')&&index<gallery.length-1)[gallery[index+1],gallery[index]]=[gallery[index],gallery[index+1]];renderGallery()});
  let dragIndex=null;el('#vehicle-gallery').addEventListener('dragstart',e=>dragIndex=+e.target.closest('[data-gallery-index]')?.dataset.galleryIndex);el('#vehicle-gallery').addEventListener('dragover',e=>e.preventDefault());el('#vehicle-gallery').addEventListener('drop',e=>{e.preventDefault();const target=+e.target.closest('[data-gallery-index]')?.dataset.galleryIndex;if(Number.isInteger(dragIndex)&&Number.isInteger(target)&&dragIndex!==target)gallery.splice(target,0,...gallery.splice(dragIndex,1));dragIndex=null;renderGallery()});
  all('[name="vehicle_type"]').forEach(radio=>radio.onchange=()=>syncType(true));el('#close-vehicle').onclick=el('#cancel-vehicle').onclick=()=>dialog.close();
  const formatInteger=value=>Number(value||0).toLocaleString('pt-BR');
  function setCurrency(field,value){const raw=digits(value);field.dataset.raw=raw?String(Number(raw)):'';field.value=raw?`${formatInteger(raw)},00`:'';const hidden=el(`[name="${field.dataset.currency}"]`);if(hidden)hidden.value=field.dataset.raw;const preview=field.closest('label')?.querySelector('.money-preview');if(preview)preview.textContent=raw?`${window.LDP_CURRENCY.format(Number(raw))}/mês`:''}
  function bindCurrency(field){field.addEventListener('focus',()=>field.select());field.addEventListener('keydown',event=>{if(event.ctrlKey||event.metaKey||event.altKey||['Tab','ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const selectedAll=field.selectionStart===0&&field.selectionEnd===field.value.length;if(/^\d$/.test(event.key)){event.preventDefault();setCurrency(field,(selectedAll?'':field.dataset.raw||'')+event.key)}else if(event.key==='Backspace'||event.key==='Delete'){event.preventDefault();setCurrency(field,selectedAll?'':(field.dataset.raw||'').slice(0,-1))}else event.preventDefault()});field.addEventListener('paste',event=>{event.preventDefault();setCurrency(field,event.clipboardData.getData('text'))})}
  const mileageField=el('[name="mileage"]'),mileagePreview=el('[data-preview="mileage"]');mileageField.addEventListener('input',()=>{const value=Number(digits(mileageField.value));mileagePreview.textContent=value?`${formatInteger(value)} km`:''});all('[data-currency]').forEach(bindCurrency);const showVehicleDialog=dialog.showModal.bind(dialog);dialog.showModal=()=>{showVehicleDialog();setTimeout(()=>all('[data-currency]').forEach(field=>setCurrency(field,el(`[name="${field.dataset.currency}"]`).value)),0)};
  el('#add-feature').onclick=()=>{const field=el('#custom-feature'),value=field.value.trim();if(!value)return;const selected=[...selectedFeatures(),value];renderFeatures(selected);field.value=''};
  function storagePath(url){try{const marker='/storage/v1/object/public/vehicle-images/';const value=new URL(url).pathname;return value.includes(marker)?decodeURIComponent(value.split(marker)[1]):null}catch{return null}}
  function openEditor(vehicle=null){form.reset();gallery=[];removedStorage=[];el('[name="vehicle_type"][value="car"]').checked=true;el('[name="active"]').checked=true;el('[name="keep_sold_public"]').checked=true;el('#dialog-title').textContent=vehicle?'Editar veículo':'Novo veículo';syncType();if(vehicle){['id','brand','model','version','year','color','mileage','price','installment','status','category','highlight_category','highlight_position','home_position','description'].forEach(name=>{if(el(`[name="${name}"]`))el(`[name="${name}"]`).value=vehicle[name]??''});const currentType=vehicle.vehicle_type||'car';el(`[name="vehicle_type"][value="${currentType}"]`).checked=true;syncType();el('[name="body_type"]').value=opts.bodyTypes[currentType].includes(vehicle.body_type)?vehicle.body_type:'';el('[name="transmission"]').value=vehicle.transmission||opts.transmissions[currentType][0];el('[name="fuel"]').value=vehicle.fuel||opts.fuels[currentType][0];['featured','newly_arrived','keep_sold_public','active'].forEach(name=>el(`[name="${name}"]`).checked=!!vehicle[name]);renderFeatures(vehicle.features||[]);all('[name="tag_choice"]').forEach(x=>x.checked=(vehicle.tags||[]).includes(x.value));gallery=[...new Set([vehicle.image_url,...(vehicle.image_urls||[])].filter(Boolean))].map(url=>({url,storagePath:storagePath(url)}));['mileage','price','installment'].forEach(name=>el(`[name="${name}"]`).dispatchEvent(new Event('input')))}renderGallery();setStatus('');dialog.showModal()}
  document.addEventListener('click',e=>{if(e.target.closest('#new-vehicle')){e.preventDefault();e.stopImmediatePropagation();openEditor()}const edit=e.target.closest('[data-edit]');if(edit){e.preventDefault();e.stopImmediatePropagation();const source=typeof allVehicles!=='undefined'?allVehicles:(window.__allAdminVehicles||[]);openEditor(source.find(v=>String(v.id)===edit.dataset.edit)||null)}},true);
  const originalRender=window.renderVehicles;if(typeof originalRender==='function')window.renderVehicles=list=>{window.__allAdminVehicles=list;originalRender(list)};
  async function upload(item,index,slug){if(!item.file)return item.url;const{data:{user}}=await window.supabaseClient.auth.getUser();if(!user)throw new Error('Sua sessão expirou. Entre novamente.');const extension=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif'})[item.file.type];if(!extension)throw new Error('Formato de imagem não permitido.');const path=`${user.id}/${slug}/${Date.now()}-${index}-${crypto.randomUUID()}.${extension}`;const{error}=await window.supabaseClient.storage.from('vehicle-images').upload(path,item.file,{cacheControl:'31536000',upsert:false,contentType:item.file.type});if(error)throw new Error(error.message.includes('Bucket not found')?'O armazenamento de fotos ainda não foi ativado. Execute a migração do Storage no Supabase.':'Não foi possível enviar uma das fotos. Tente novamente.');return window.supabaseClient.storage.from('vehicle-images').getPublicUrl(path).data.publicUrl}
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(e.submitter?.value==='cancel'){dialog.close();return}if(!form.reportValidity())return;const button=el('#save-vehicle');if(button.disabled)return;button.disabled=true;button.textContent='Salvando…';setStatus('Enviando fotos e salvando o veículo…');try{const d=Object.fromEntries(new FormData(form)),kind=type(),body=d.body_type;if(!opts.bodyTypes[kind].includes(body))throw new Error('Selecione um tipo de veículo compatível.');const slug=`${d.brand}-${d.model}-${d.version||''}-${d.year}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const urls=[];for(let i=0;i<gallery.length;i++)urls.push(await upload(gallery[i],i,slug));const automatic=[kind==='car'?'Carro':'Moto',body,d.transmission,d.fuel];const tags=[...new Set([...automatic,...all('[name="tag_choice"]:checked').map(x=>x.value)].filter(Boolean))];const payload={vehicle_type:kind,brand:d.brand.trim(),model:d.model.trim(),version:d.version?.trim()||null,year:+d.year,mileage:digits(d.mileage)?+digits(d.mileage):0,price:digits(d.price)?+digits(d.price):null,installment:digits(d.installment)?+digits(d.installment):null,status:d.status,transmission:d.transmission||null,fuel:d.fuel||null,color:d.color||null,category:d.category||null,body_type:body,highlight_category:d.highlight_category||null,highlight_position:d.highlight_position?+d.highlight_position:null,home_position:d.home_position?+d.home_position:null,image_url:urls[0]||null,image_urls:urls.slice(1),description:d.description?.trim()||null,features:selectedFeatures(),tags,lifestyle_categories:[],slug,featured:el('[name="featured"]').checked,newly_arrived:el('[name="newly_arrived"]').checked,keep_sold_public:el('[name="keep_sold_public"]').checked,active:el('[name="active"]').checked};const query=d.id?window.supabaseClient.from('vehicles').update(payload).eq('id',d.id):window.supabaseClient.from('vehicles').insert(payload);const{error}=await query;if(error)throw new Error('Não foi possível salvar o veículo. Revise os campos e tente novamente.');if(removedStorage.length)await window.supabaseClient.storage.from('vehicle-images').remove(removedStorage);setStatus('Veículo salvo com sucesso.');await window.loadVehicles();setTimeout(()=>dialog.close(),650)}catch(error){setStatus(error.message||'Não foi possível salvar o veículo.',true)}finally{button.disabled=false;button.textContent='Salvar veículo'}},true);
  syncType();
})();
