const client=window.supabaseClient;let allVehicles=[],currentUser=null,accessPoll=null;const OWNER_EMAIL='andrenevessato04@gmail.com';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const money=n=>n?Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}):'Não informado';
function status(msg,error=false,root=document){const el=root.querySelector('.status');if(el){el.textContent=msg;el.style.color=error?'#e66':'#24bd69'}}
async function init(){if(!client){status('Supabase ainda não foi configurado.',true);return}const{data:{session}}=await client.auth.getSession();session?authorize(session.user):showAuth();client.auth.onAuthStateChange((event,s)=>{if(event==='INITIAL_SESSION')return;setTimeout(()=>s?authorize(s.user):showAuth(),0)})}
function stopAccessPoll(){if(accessPoll){clearInterval(accessPoll);accessPoll=null}}
function showAuth(){stopAccessPoll();$('#auth-view').classList.remove('hidden');$('#app-view').classList.add('hidden');$('#access-lock').classList.add('hidden')}
function showBlocked(user,state='pending'){currentUser=user;$('#auth-view').classList.add('hidden');$('#app-view').classList.add('hidden');$('#access-lock').classList.remove('hidden');$('#access-lock-email').textContent=user.email||'';const rejected=state==='rejected';$('#access-lock-title').textContent=rejected?'Acesso não autorizado':'Acesso aguardando aprovação';$('#access-lock-message').textContent=rejected?'Seu pedido não foi aprovado. Fale com o administrador da Loja do Preto para solicitar uma nova análise.':'Seu cadastro foi recebido. O painel será liberado somente depois que o administrador aprovar seu acesso.';$('.access-lock-pulse').classList.toggle('hidden',rejected);stopAccessPoll();if(!rejected)accessPoll=setInterval(()=>authorize(user,{silent:true}),5000)}
async function authorize(user,{silent=false}={}){if((user.email||'').toLowerCase()===OWNER_EMAIL){await showApp(user);return}const{data,error}=await client.from('admin_access_requests').select('status').eq('user_id',user.id).maybeSingle();if(!error&&data?.status==='approved'){stopAccessPoll();await showApp(user);return}showBlocked(user,data?.status||'pending');if(error&&!silent)$('#access-lock-message').textContent='Não foi possível consultar a aprovação agora. O painel continuará verificando automaticamente.'}
async function showApp(user){stopAccessPoll();currentUser=user;$('#auth-view').classList.add('hidden');$('#access-lock').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-email').textContent=user.email;const isOwner=user.email.toLowerCase()===OWNER_EMAIL;$('#access-tab').classList.toggle('hidden',!isOwner);await Promise.all([loadVehicles(),loadSettings(),isOwner?loadAccessRequests():Promise.resolve()])}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();status('Entrando…');const d=new FormData(e.target);const{error}=await client.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});status(error?error.message:'Login realizado.',!!error)});
const passwordInput=$('#password-input'),togglePassword=$('#toggle-password');
passwordInput.addEventListener('input',()=>{togglePassword.hidden=!passwordInput.value;if(!passwordInput.value){passwordInput.type='password';togglePassword.setAttribute('aria-label','Mostrar senha');togglePassword.title='Mostrar senha'}});
togglePassword.addEventListener('click',()=>{const willShow=passwordInput.type==='password';passwordInput.type=willShow?'text':'password';const label=willShow?'Ocultar senha':'Mostrar senha';togglePassword.setAttribute('aria-label',label);togglePassword.title=label;passwordInput.focus()});
$('#signup').onclick=()=>{window.location.href='/admin/cadastro.html'};const recoveryButton=document.createElement('button');recoveryButton.type='button';recoveryButton.className='secondary';recoveryButton.textContent='Esqueci minha senha';recoveryButton.onclick=()=>{window.location.href='/admin/recuperar.html'};$('#signup').insertAdjacentElement('afterend',recoveryButton);$('#logout').onclick=()=>client.auth.signOut();$('#access-lock-logout').onclick=()=>client.auth.signOut();
function changeTab(tab){$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==tab));$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#page-title').textContent={dashboard:'Visão geral',vehicles:'Veículos',access:'Novos acessos',settings:'Configurações'}[tab];if(tab==='access')loadAccessRequests()}
$$('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>changeTab(b.dataset.go));
async function loadVehicles(){const{data,error}=await client.from('vehicles').select('*').order('created_at',{ascending:false});if(error){alert(error.message);return}allVehicles=data||[];renderVehicles(allVehicles);$('#stat-total').textContent=allVehicles.length;$('#stat-active').textContent=allVehicles.filter(v=>v.active).length;$('#stat-featured').textContent=allVehicles.filter(v=>v.featured).length}
function renderVehicles(list){$('#vehicle-count').textContent=`${list.length} veículo${list.length===1?'':'s'}`;$('#admin-empty').classList.toggle('hidden',list.length>0);$('#vehicle-list').innerHTML=list.map(v=>`<tr><td><div class="vehicle-name"><img src="${v.image_url||'https://raw.githubusercontent.com/Sato190/loja-do-preto/main/assets/hero-showroom.jpg'}" alt=""><div><b>${v.brand} ${v.model}</b><small>${(v.vehicle_type||'car')==='motorcycle'?'Moto':'Carro'} • ${v.version||'Versão a definir'}${v.newly_arrived?' • Novo no estoque':''}</small></div></div></td><td>${v.year}</td><td>${money(v.price)}</td><td><span class="badge ${v.active?'':'off'}">${v.active?({available:'Disponível',reserved:'Reservado',sold:'Vendido'}[v.status||'available']):'Oculto'}</span></td><td><div class="actions"><button data-edit="${v.id}">Editar</button><button class="delete" data-delete="${v.id}">Excluir</button></div></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openVehicle(allVehicles.find(v=>v.id===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>removeVehicle(b.dataset.delete))}
$('#search').oninput=e=>{const q=e.target.value.toLowerCase();renderVehicles(allVehicles.filter(v=>`${v.brand} ${v.model} ${v.version}`.toLowerCase().includes(q)))};
const dialog=$('#vehicle-dialog'),form=$('#vehicle-form');form.querySelector('[name="category"]').closest('label').insertAdjacentHTML('beforebegin','<label>Tipo de veículo<select name="vehicle_type"><option value="car">Carro</option><option value="motorcycle">Moto</option></select></label>');form.querySelector('[name="category"]').closest('label').insertAdjacentHTML('afterend','<label>Carroceria<input name="body_type" placeholder="SUV, cupê, picape..."></label><label>Categoria de destaque<select name="highlight_category"><option value="">Sem categoria</option><option>Premium</option><option>Luxo</option><option>Esportivo</option><option>Escolha da Loja</option><option>Novidade</option><option>Oportunidade</option></select></label><label>Ordem nos destaques<input name="highlight_position" type="number" min="1"></label><label>Posição na Home<input name="home_position" type="number" min="1"></label>');form.elements.status.insertAdjacentHTML('beforeend','<option value="preparing">Em preparação</option>');$('#new-vehicle').onclick=()=>openVehicle();function openVehicle(v){form.reset();form.active.checked=true;form.keep_sold_public.checked=true;$('#dialog-title').textContent=v?'Editar veículo':'Novo veículo';if(v){for(const[k,val]of Object.entries(v)){if(!form.elements[k])continue;if(form.elements[k].type==='checkbox')form.elements[k].checked=!!val;else form.elements[k].value=['features','image_urls','tags','lifestyle_categories'].includes(k)?(val||[]).join('\n'):(val??'')}}dialog.showModal()}
form.addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return;const d=Object.fromEntries(new FormData(form)),lines=name=>d[name]?d[name].split('\n').map(x=>x.trim()).filter(Boolean):[];const slug=`${d.brand}-${d.model}-${d.version||''}-${d.year}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const payload={vehicle_type:d.vehicle_type||'car',brand:d.brand,model:d.model,version:d.version||null,year:+d.year,mileage:d.mileage?+d.mileage:0,price:d.price?+d.price:null,installment:d.installment?+d.installment:null,status:d.status||'available',transmission:d.transmission||null,fuel:d.fuel||null,color:d.color||null,category:d.category||null,body_type:d.body_type||null,highlight_category:d.highlight_category||null,highlight_position:d.highlight_position?+d.highlight_position:null,home_position:d.home_position?+d.home_position:null,image_url:d.image_url||null,image_urls:lines('image_urls'),description:d.description||null,features:lines('features'),tags:lines('tags'),lifestyle_categories:lines('lifestyle_categories'),slug,featured:form.featured.checked,newly_arrived:form.newly_arrived.checked,keep_sold_public:form.keep_sold_public.checked,active:form.active.checked};status('Salvando…',false,form);const query=d.id?client.from('vehicles').update(payload).eq('id',d.id):client.from('vehicles').insert(payload);const{error}=await query;if(error){status(error.message,true,form);return}dialog.close();await loadVehicles()});
async function removeVehicle(id){if(!confirm('Excluir este veículo permanentemente?'))return;const{error}=await client.from('vehicles').delete().eq('id',id);if(error)alert(error.message);else loadVehicles()}
$('#settings-form button[type="submit"]').insertAdjacentHTML('beforebegin','<label class="wide"><strong>Nossa história — título</strong><input name="history_title" placeholder="Nossa história"></label><label class="wide">Subtítulo institucional<input name="history_subtitle"></label><label class="wide">Texto da história<textarea name="history_text" rows="7" placeholder="Escreva somente informações reais sobre a trajetória da loja."></textarea></label><label>Logo institucional (URL)<input name="history_logo_url" type="url"></label><label>Imagem institucional (URL)<input name="history_image_url" type="url"></label><label class="wide">Galeria institucional<textarea name="history_gallery" rows="4" placeholder="Uma URL por linha"></textarea></label><label class="wide">Linha do tempo<textarea name="history_timeline" rows="5" placeholder="Ano | Título | Texto — uma etapa por linha"></textarea></label><label class="wide">Valores da loja<textarea name="store_values" rows="5" placeholder="Título | Texto — um valor por linha"></textarea></label><label class="wide">Equipe<textarea name="team_members" rows="5" placeholder="Nome | Função | Foto URL | WhatsApp"></textarea></label><label class="wide">Perguntas frequentes<textarea name="faqs" rows="6" placeholder="Pergunta | Resposta — uma por linha"></textarea></label><label class="wide">Categorias de descoberta<textarea name="lifestyle_categories" rows="4" placeholder="Primeiro carro — uma por linha"></textarea></label>');
async function loadSettings(){const{data}=await client.from('store_settings').select('*').eq('id',1).maybeSingle();if(data)for(const[k,v]of Object.entries(data))if($('#settings-form').elements[k])$('#settings-form').elements[k].value=k==='faqs'?(v||[]).map(x=>`${x.question||''} | ${x.answer||''}`).join('\n'):['lifestyle_categories','history_gallery'].includes(k)?(v||[]).join('\n'):k==='history_timeline'?(v||[]).map(x=>`${x.year||''} | ${x.title||''} | ${x.text||''}`).join('\n'):k==='store_values'?(v||[]).map(x=>`${x.title||''} | ${x.text||''}`).join('\n'):k==='team_members'?(v||[]).map(x=>`${x.name||''} | ${x.role||''} | ${x.image||''} | ${x.whatsapp||''}`).join('\n'):(v||'')}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));payload.id=1;const rows=name=>(payload[name]||'').split('\n').map(x=>x.trim()).filter(Boolean);payload.faqs=rows('faqs').map(line=>{const[question,...answer]=line.split('|');return{question:question?.trim(),answer:answer.join('|').trim()}}).filter(x=>x.question&&x.answer);payload.lifestyle_categories=rows('lifestyle_categories');payload.history_gallery=rows('history_gallery');payload.history_timeline=rows('history_timeline').map(line=>{const[year,title,...text]=line.split('|');return{year:year?.trim(),title:title?.trim(),text:text.join('|').trim()}});payload.store_values=rows('store_values').map(line=>{const[title,...text]=line.split('|');return{title:title?.trim(),text:text.join('|').trim()}});payload.team_members=rows('team_members').map(line=>{const[name,role,image,whatsapp]=line.split('|');return{name:name?.trim(),role:role?.trim(),image:image?.trim(),whatsapp:whatsapp?.trim()}});status('Salvando…',false,e.target);const{error}=await client.from('store_settings').upsert(payload);status(error?error.message:'Configurações publicadas com sucesso.',!!error,e.target)});
async function loadAccessRequests(){if(!currentUser||currentUser.email.toLowerCase()!==OWNER_EMAIL)return;const{data,error}=await client.from('admin_access_requests').select('*').neq('email',OWNER_EMAIL).order('requested_at',{ascending:false});if(error){status(error.message,true,$('[data-panel="access"]'));return}const requests=data||[],pending=requests.filter(r=>r.status==='pending').length;$('#access-count').textContent=pending;$('#access-count').classList.toggle('hidden',pending===0);$('#access-empty').classList.toggle('hidden',requests.length>0);$('#access-list').innerHTML=requests.map(r=>`<tr><td><b>${escapeHtml(r.email)}</b></td><td>${new Date(r.requested_at).toLocaleString('pt-BR')}</td><td><span class="badge access-${r.status}">${{pending:'Pendente',approved:'Aprovado',rejected:'Recusado'}[r.status]}</span></td><td><div class="actions">${r.status!=='approved'?`<button class="approve" data-access="approved" data-user="${r.user_id}">Aprovar</button>`:''}${r.status!=='rejected'?`<button class="delete" data-access="rejected" data-user="${r.user_id}">Recusar</button>`:''}</div></td></tr>`).join('');$$('[data-access]').forEach(b=>b.onclick=()=>reviewAccess(b.dataset.user,b.dataset.access))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function reviewAccess(userId,nextStatus){const action=nextStatus==='approved'?'aprovar':'recusar';if(!confirm(`Deseja ${action} este acesso?`))return;status('Atualizando acesso…',false,$('[data-panel="access"]'));const{error}=await client.from('admin_access_requests').update({status:nextStatus,reviewed_at:new Date().toISOString(),reviewed_by:currentUser.id}).eq('user_id',userId);status(error?error.message:nextStatus==='approved'?'Acesso aprovado. A pessoa já pode entrar.':'Acesso recusado.',!!error,$('[data-panel="access"]'));if(!error)loadAccessRequests()}
$('#refresh-access').onclick=loadAccessRequests;
if(new URLSearchParams(location.search).get('confirmed'))status('E-mail confirmado. Entre para consultar a aprovação do seu acesso.');
init();



