import {cors,json,normalizeLogin,validLogin,technicalEmail,requireOwner} from './accounts.ts';
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const auth=await requireOwner(req);if(!auth)return json({error:'not_authorized'},403);const body=await req.json().catch(()=>({})),action=String(body.action||'list'),db=auth.db;
 try{
  if(action==='list'){const{data,error}=await db.from('admin_profiles').select('user_id,login,display_name,role,status,active,last_login_at,created_at,removed_at').order('created_at');if(error)throw error;return json({accounts:data})}
  if(action==='create'){const login=normalizeLogin(body.login),name=String(body.name||'').trim(),password=String(body.password||''),role=['owner','manager','marketing','sales'].includes(body.role)?body.role:'sales';if(!validLogin(login))return json({error:'invalid_login'},400);if(name.length<2||name.length>100)return json({error:'invalid_name'},400);if(password.length<12||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password))return json({error:'weak_password'},400);const{data:exists}=await db.from('admin_profiles').select('user_id').ilike('login',login).maybeSingle();if(exists)return json({error:'login_in_use'},409);const{data:created,error:createError}=await db.auth.admin.createUser({email:technicalEmail(login),password,email_confirm:true,user_metadata:{display_name:name,login}});if(createError)throw createError;const{error:profileError}=await db.from('admin_profiles').upsert({user_id:created.user.id,email:technicalEmail(login),login,display_name:name,role,active:true,status:'active',disabled_at:null,removed_at:null});if(profileError){await db.auth.admin.deleteUser(created.user.id);throw profileError}await db.from('security_events').insert({event_type:'account_created',severity:'info',source:'admin-accounts',summary:`Conta ${login} criada`,metadata:{actor_id:auth.user.id,target_id:created.user.id,role}});return json({ok:true})}
  const userId=String(body.user_id||'');const{data:target}=await db.from('admin_profiles').select('user_id,role,login,status').eq('user_id',userId).maybeSingle();if(!target)return json({error:'account_not_found'},404);if(target.user_id===auth.user.id&&['disable','remove'].includes(action))return json({error:'cannot_remove_self'},409);if(target.role==='owner'&&['disable','remove'].includes(action)){const{count}=await db.from('admin_profiles').select('*',{count:'exact',head:true}).eq('role','owner').eq('active',true).eq('status','active');if((count||0)<=1)return json({error:'last_owner'},409)}
  if(action==='disable'||action==='remove'){const removed=action==='remove',now=new Date().toISOString();await db.from('admin_profiles').update({active:false,status:removed?'removed':'disabled',disabled_at:now,removed_at:removed?now:null}).eq('user_id',userId);await db.auth.admin.updateUserById(userId,{ban_duration:'876000h'});await db.from('security_events').insert({event_type:removed?'account_removed':'account_disabled',severity:'warning',source:'admin-accounts',summary:`Conta ${target.login} ${removed?'removida':'desativada'}`,metadata:{actor_id:auth.user.id,target_id:userId}});return json({ok:true})}
  if(action==='enable'){await db.auth.admin.updateUserById(userId,{ban_duration:'none'});await db.from('admin_profiles').update({active:true,status:'active',disabled_at:null,removed_at:null}).eq('user_id',userId);return json({ok:true})}
  if(action==='password'){const password=String(body.password||'');if(password.length<12||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password))return json({error:'weak_password'},400);const{error}=await db.auth.admin.updateUserById(userId,{password});if(error)throw error;await db.from('security_events').insert({event_type:'password_changed',severity:'info',source:'admin-accounts',summary:`Senha da conta ${target.login} alterada`,metadata:{actor_id:auth.user.id,target_id:userId}});return json({ok:true})}
  return json({error:'invalid_action'},400)
 }catch(error){console.error('admin-accounts',error instanceof Error?error.message:'error');return json({error:'operation_failed'},500)}});
